/**
 * 为历史人物种子补全 gender / geography / birthCertainty，并追加多样性条目。
 * 运行：node scripts/enrich-figures.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { EXTRA2 } from "./figures-batch2.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataPath = path.join(__dirname, "../data/historical-figures.json");

const META = {
  einstein: { gender: "male", country: "德国", region: "巴登-符腾堡", birthPlace: "乌尔姆" },
  curie: { gender: "female", country: "波兰/法国", region: "华沙", birthPlace: "华沙" },
  newton: { gender: "male", country: "英国", region: "英格兰", birthPlace: "伍尔斯索普" },
  turing: { gender: "male", country: "英国", region: "英格兰", birthPlace: "伦敦" },
  lincoln: { gender: "male", country: "美国", region: "肯塔基", birthPlace: "霍金维尔附近" },
  churchill: { gender: "male", country: "英国", region: "英格兰", birthPlace: "布莱尼姆宫" },
  "sun-yat-sen": { gender: "male", country: "中国", region: "广东", birthPlace: "香山（中山）" },
  luxun: { gender: "male", country: "中国", region: "浙江", birthPlace: "绍兴" },
  "zhou-enlai": { gender: "male", country: "中国", region: "江苏", birthPlace: "淮安" },
  "deng-xiaoping": { gender: "male", country: "中国", region: "四川", birthPlace: "广安" },
  "mao-zedong": { gender: "male", country: "中国", region: "湖南", birthPlace: "湘潭韶山" },
  caesar: { gender: "male", country: "古罗马", region: "意大利半岛", birthPlace: "罗马" },
  confucius: { gender: "male", country: "中国", region: "鲁国/山东", birthPlace: "曲阜附近" },
  "qu-yuan": { gender: "male", country: "中国", region: "楚国/湖北一带", birthPlace: "丹阳一带（传统说法）" },
  "sima-qian": { gender: "male", country: "中国", region: "陕西", birthPlace: "龙门（韩城）" },
  "zhuge-liang": { gender: "male", country: "中国", region: "山东/琅邪", birthPlace: "阳都（传统）" },
  "li-bai": { gender: "male", country: "中国", region: "碎叶/蜀地关联", birthPlace: "碎叶城一带（传统）" },
  "du-fu": { gender: "male", country: "中国", region: "河南", birthPlace: "巩县" },
  "su-shi": { gender: "male", country: "中国", region: "四川", birthPlace: "眉山" },
  "yue-fei": { gender: "male", country: "中国", region: "河南", birthPlace: "汤阴" },
  "zhu-xi": { gender: "male", country: "中国", region: "福建", birthPlace: "尤溪" },
  "wang-yangming": { gender: "male", country: "中国", region: "浙江", birthPlace: "余姚" },
  "hai-rui": { gender: "male", country: "中国", region: "海南", birthPlace: "琼山" },
  "li-shizhen": { gender: "male", country: "中国", region: "湖北", birthPlace: "蕲州" },
  "zhang-juzheng": { gender: "male", country: "中国", region: "湖北", birthPlace: "江陵" },
  "cao-xueqin": { gender: "male", country: "中国", region: "北京/江南关联", birthPlace: "江宁织造背景" },
  "zeng-guofan": { gender: "male", country: "中国", region: "湖南", birthPlace: "湘乡" },
  "hu-xueyan": { gender: "male", country: "中国", region: "安徽/杭州经营", birthPlace: "绩溪" },
  "qi-baishi": { gender: "male", country: "中国", region: "湖南", birthPlace: "湘潭" },
  "mei-lanfang": { gender: "male", country: "中国", region: "北京/江苏关联", birthPlace: "北京" },
  "lei-feng": { gender: "male", country: "中国", region: "湖南", birthPlace: "望城" },
  shakespeare: { gender: "male", country: "英国", region: "英格兰", birthPlace: "斯特拉特福" },
  "van-gogh": { gender: "male", country: "荷兰", region: "北布拉班特", birthPlace: "津德尔特" },
  michelangelo: { gender: "male", country: "意大利", region: "托斯卡纳", birthPlace: "卡普雷塞" },
  "ada-lovelace": { gender: "female", country: "英国", region: "英格兰", birthPlace: "伦敦" },
  nightingale: { gender: "female", country: "英国", region: "托斯卡纳出生/英国活动", birthPlace: "佛罗伦萨" },
  gandhi: { gender: "male", country: "印度", region: "古吉拉特", birthPlace: "博尔班达尔" },
  mandela: { gender: "male", country: "南非", region: "东开普", birthPlace: "姆韦佐" },
  tesla: { gender: "male", country: "奥匈/美国", region: "斯米连", birthPlace: "斯米连" },
  rockefeller: { gender: "male", country: "美国", region: "纽约州", birthPlace: "里奇福德" },
  "tu-youyou": { gender: "female", country: "中国", region: "浙江", birthPlace: "宁波" },
  "bei-dao": { gender: "male", country: "中国", region: "北京", birthPlace: "北京" },
  "ban-zhao": { gender: "female", country: "中国", region: "陕西/扶风", birthPlace: "安陵一带" },
  "hua-mullan": { gender: "female", country: "中国", region: "传说华北", birthPlace: "传说地（不确）" },
  "zheng-he": { gender: "male", country: "中国", region: "云南", birthPlace: "昆明滇池一带" },
  "shen-kuo": { gender: "male", country: "中国", region: "浙江", birthPlace: "钱塘" },
  "li-qingzhao": { gender: "female", country: "中国", region: "山东", birthPlace: "章丘" },
  kangxi: { gender: "male", country: "中国", region: "北京", birthPlace: "北京紫禁城" },
  "empress-wu": { gender: "female", country: "中国", region: "山西", birthPlace: "文水" },
  "guo-moruo": { gender: "male", country: "中国", region: "四川", birthPlace: "乐山" },
  "liang-qichao": { gender: "male", country: "中国", region: "广东", birthPlace: "新会" },
  "tan-sitong": { gender: "male", country: "中国", region: "湖南", birthPlace: "浏阳" },
  "song-qingling": { gender: "female", country: "中国", region: "上海/广东关联", birthPlace: "上海" },
  hypatia: { gender: "female", country: "东罗马帝国", region: "埃及亚历山大", birthPlace: "亚历山大" },
  aviccena: { gender: "male", country: "波斯/中亚", region: "布哈拉一带", birthPlace: "阿夫沙纳" },
  "zheng-banqiao": { gender: "male", country: "中国", region: "江苏", birthPlace: "兴化" },
  "lin-zexu": { gender: "male", country: "中国", region: "福建", birthPlace: "侯官" },
};

function precisionToCertainty(p) {
  if (p === "exact-date") return "exact";
  if (p === "year-month" || p === "year-only") return "year-only";
  if (p === "uncertain") return "disputed";
  return "legendary";
}

function fitDetailFrom(fig) {
  const label = fig.fitAssessment;
  if (label === "符合") {
    return { fitsNarrative: true, tensionNotes: fig.analysisNotes };
  }
  if (label === "部分符合") {
    return { fitsNarrative: "partial", tensionNotes: fig.analysisNotes };
  }
  if (label === "不符合") {
    return { fitsNarrative: false, tensionNotes: fig.analysisNotes };
  }
  return {
    fitsNarrative: "partial",
    tensionNotes: fig.analysisNotes || "出生或事迹证据不足以支撑强结论。",
  };
}

const EXTRA = [
  {
    id: "qiu-jin",
    name: "秋瑾",
    nameEn: "Qiu Jin",
    gender: "female",
    era: "1875–1907",
    dynastyOrPeriod: "晚清",
    country: "中国",
    region: "浙江",
    birthPlace: "厦门出生、绍兴成长",
    socialClass: "士族女性革命者",
    field: ["政治", "文学", "社会运动"],
    birth: {
      year: 1875,
      month: 11,
      day: 8,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "公历生卒常见于年谱；时辰未作为可靠字段收录。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["女杰", "革命牺牲", "诗文并传"],
    },
    bio: "晚清女革命家、诗人，倡导妇女解放。",
    situation: "留学日本后投身反清活动，就义于绍兴。",
    fitAssessment: "部分符合",
    analysisNotes:
      "常被附会为‘杀破狼式烈性’叙事。教育用途应强调性别与政治结构压力，而非用神验证。",
    classicalRefs: ["子平：官杀与性情标签不可等同革命史"],
    sources: ["秋瑾年谱通行材料", "清史相关公开叙述"],
    counterexample: false,
  },
  {
    id: "darwin",
    name: "查尔斯·达尔文",
    nameEn: "Charles Darwin",
    gender: "male",
    era: "1809–1882",
    dynastyOrPeriod: "19 世纪英国",
    country: "英国",
    region: "英格兰",
    birthPlace: "什鲁斯伯里",
    socialClass: "士绅学者",
    field: ["科学", "生物学"],
    birth: {
      year: 1809,
      month: 2,
      day: 12,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["长期观察", "理论突破", "争议与接受并存"],
    },
    bio: "进化论主要奠基者之一。",
    situation: "环球航行后长期整理证据，晚年开始广泛影响生物学与社会思想。",
    fitAssessment: "部分符合",
    analysisNotes:
      "‘印食生慧’类比易套用。科学革命更依赖航海、标本网络与同行评议制度。",
    classicalRefs: ["滴天髓：才学须看印食，亦须看际遇"],
    sources: ["Britannica: Charles Darwin"],
    counterexample: false,
  },
  {
    id: "frida-kahlo",
    name: "弗里达·卡罗",
    nameEn: "Frida Kahlo",
    gender: "female",
    era: "1907–1954",
    dynastyOrPeriod: "20 世纪拉美",
    country: "墨西哥",
    region: "墨西哥城",
    birthPlace: "科约阿坎",
    socialClass: "艺术家",
    field: ["艺术"],
    birth: {
      year: 1907,
      month: 7,
      day: 6,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["伤痛与创作", "身份政治", "自传性绘画"],
    },
    bio: "墨西哥现代艺术代表人物，以自画像闻名。",
    situation: "车祸与慢性病背景下坚持创作，作品成为拉美与女性主义视觉符号。",
    fitAssessment: "部分符合",
    analysisNotes:
      "伤官、疾厄类附会常见。反确认偏误提醒：身体创伤与艺术语言的关系不能简化为格局断语。",
    classicalRefs: ["三命通会：疾厄与才艺须分论"],
    sources: ["Frida Kahlo Museum / 公开传记年表"],
    counterexample: false,
  },
  {
    id: "tagore",
    name: "罗宾德拉纳特·泰戈尔",
    nameEn: "Rabindranath Tagore",
    gender: "male",
    era: "1861–1941",
    dynastyOrPeriod: "近现代南亚",
    country: "印度",
    region: "孟加拉",
    birthPlace: "加尔各答",
    socialClass: "士绅文人",
    field: ["文学", "教育", "思想"],
    birth: {
      year: 1861,
      month: 5,
      day: 7,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["诗哲", "跨文化影响", "教育实验"],
    },
    bio: "孟加拉语文学巨匠，亚洲首位诺贝尔文学奖得主。",
    situation: "以诗歌、戏剧与教育实践影响南亚现代文化，并参与公共思想论争。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤生秀的叙事易贴合，但殖民语境下的文化资本同样关键。",
    classicalRefs: ["食伤为文艺表达之常用类比"],
    sources: ["Nobel Prize biography: Rabindranath Tagore"],
    counterexample: false,
  },
  {
    id: "martin-luther",
    name: "马丁·路德",
    nameEn: "Martin Luther",
    gender: "male",
    era: "1483–1546",
    dynastyOrPeriod: "宗教改革时代",
    country: "德意志",
    region: "萨克森-安哈尔特",
    birthPlace: "艾斯莱本",
    socialClass: "教士/改革者",
    field: ["宗教", "思想"],
    birth: {
      year: 1483,
      month: 11,
      day: 10,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "传统记载生日；时辰未知。儒略/格里换算在早期文献中需注意。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["宗教改革", "对抗权威", "印刷传播"],
    },
    bio: "宗教改革关键人物，《九十五条论纲》传统关联者。",
    situation: "挑战罗马教廷权威，引发欧洲宗教与政治重组。",
    fitAssessment: "部分符合",
    analysisNotes:
      "七杀、伤官见官一类附会极常见。印刷术与诸侯政治才是扩散主因；标为部分符合以防神话化。",
    classicalRefs: ["子平：官杀战与叛逆标签勿直接史实化"],
    sources: ["Britannica: Martin Luther"],
    counterexample: false,
  },
  {
    id: "catherine-great",
    name: "叶卡捷琳娜二世",
    nameEn: "Catherine the Great",
    gender: "female",
    era: "1729–1796",
    dynastyOrPeriod: "俄罗斯帝国",
    country: "俄罗斯",
    region: "普鲁士出生/俄国统治",
    birthPlace: "斯德丁（今什切青）",
    socialClass: "帝王",
    field: ["政治"],
    birth: {
      year: 1729,
      month: 5,
      day: 2,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["女主执政", "开明专制争议", "宫廷政变上位"],
    },
    bio: "俄罗斯帝国女皇，以扩张与开明专制形象著称。",
    situation: "以外戚身份经政变掌权，长期主导帝国内外政策。",
    fitAssessment: "部分符合",
    analysisNotes:
      "女帝案例常被用来‘证明’某类阳刚格局。本库强调宫廷派系与地缘政治，反对单一命理解释。",
    classicalRefs: ["三命通会：女命官星说须历史化阅读"],
    sources: ["Britannica: Catherine the Great"],
    counterexample: false,
  },
  {
    id: "george-washington",
    name: "乔治·华盛顿",
    nameEn: "George Washington",
    gender: "male",
    era: "1732–1799",
    dynastyOrPeriod: "18 世纪北美",
    country: "美国",
    region: "弗吉尼亚",
    birthPlace: "威斯特摩兰县",
    socialClass: "种植园主/军人政治家",
    field: ["政治", "军事"],
    birth: {
      year: 1732,
      month: 2,
      day: 22,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "公历换算后的常用生日；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["建国领袖", "自愿交权", "军人从政"],
    },
    bio: "美国开国元勋，首任总统。",
    situation: "领导独立战争后两次出任总统并开创和平交权先例。",
    fitAssessment: "部分符合",
    analysisNotes:
      "正官得位叙事极易事后附会。制度设计与精英联盟更关键；勿当作‘交权格局’证明。",
    classicalRefs: ["渊海子平：官星清浊与权位须分看"],
    sources: ["Britannica: George Washington"],
    counterexample: false,
  },
  {
    id: "frederick-douglass",
    name: "弗雷德里克·道格拉斯",
    nameEn: "Frederick Douglass",
    gender: "male",
    era: "约 1818–1895",
    dynastyOrPeriod: "19 世纪美国",
    country: "美国",
    region: "马里兰",
    birthPlace: "塔尔博特县",
    socialClass: "奴隶出身社会活动家",
    field: ["社会运动", "文学", "政治"],
    birth: {
      year: 1818,
      hour: null,
      calendar: "gregorian",
      precision: "year-only",
      note: "出生于奴隶制下，精确月日不确；自述约 1818 年。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["奴隶解放", "演说与自传", "阶层跃迁"],
      shiShenTendency: ["伤官", "正印", "七杀"],
    },
    bio: "废奴运动领袖、作家与演说家。",
    situation: "逃出奴隶制后成为公共知识分子，推动废奴与民权。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：精确出生信息缺失却成就巨大公共影响力。说明社会结构与能动性不能被‘日柱命运’替代。",
    classicalRefs: ["子平：无确切生辰则不可硬排格局"],
    sources: ["National Park Service / Douglass 公开传记"],
    counterexample: true,
  },
  {
    id: "murasaki",
    name: "紫式部",
    nameEn: "Murasaki Shikibu",
    gender: "female",
    era: "约 973–约 1014",
    dynastyOrPeriod: "日本平安时代",
    country: "日本",
    region: "京都",
    birthPlace: "平安京",
    socialClass: "宫廷女官/文人",
    field: ["文学"],
    birth: {
      year: 973,
      hour: null,
      calendar: "traditional-approx",
      precision: "uncertain",
      note: "生年约为学界估计，不可精确排盘。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["宫廷女性书写", "长篇小说传统", "生年争议"],
      shiShenTendency: ["食神", "伤官", "正印"],
    },
    bio: "《源氏物语》作者（传统认定）。",
    situation: "以宫廷女官身份留下古典物语巅峰之作。",
    fitAssessment: "资料不足",
    analysisNotes: "东亚女性文学史关键样本，但生辰不可考，禁止伪造时柱参与高置信匹配。",
    classicalRefs: ["渊海子平：时辰不明难定全局"],
    sources: ["日本古典文学研究通行概述"],
    counterexample: false,
  },
  {
    id: "sejong",
    name: "世宗大王",
    nameEn: "Sejong the Great",
    gender: "male",
    era: "1397–1450",
    dynastyOrPeriod: "朝鲜王朝",
    country: "朝鲜",
    region: "汉阳",
    birthPlace: "汉阳",
    socialClass: "帝王",
    field: ["政治", "科学", "教育"],
    birth: {
      year: 1397,
      month: 5,
      day: 15,
      hour: null,
      calendar: "gregorian",
      precision: "uncertain",
      note: "传统纪年换算后的常见日期；历法细节存研究空间，置信中低。",
    },
    chartTags: {
      hourKnown: false,
      source: "mixed",
      confidence: "low",
      patternTags: ["创制文字", "民生与科学政策", "儒家君主形象"],
    },
    bio: "朝鲜王朝君主，推动训民正音等文化工程。",
    situation: "在集权王权框架下推动文字、天文与农业相关政策。",
    fitAssessment: "部分符合",
    analysisNotes:
      "‘文昌印星’附会常见。文字政策是制度与儒臣群体协作产物，勿单归命主。",
    classicalRefs: ["滴天髓：君相造命说须历史化"],
    sources: ["韩国史公开综述 / Britannica: Sejong"],
    counterexample: false,
  },
  {
    id: "rumi",
    name: "鲁米",
    nameEn: "Rumi",
    gender: "male",
    era: "1207–1273",
    dynastyOrPeriod: "中世纪伊斯兰世界",
    country: "波斯/安纳托利亚",
    region: "巴尔赫—科尼亚",
    birthPlace: "巴尔赫一带（传统）",
    socialClass: "苏菲导师/诗人",
    field: ["宗教", "文学"],
    birth: {
      year: 1207,
      month: 9,
      day: 30,
      hour: null,
      calendar: "gregorian",
      precision: "uncertain",
      note: "传统纪念日期广泛流传；历史精确性仍有讨论，故置信偏低。",
    },
    chartTags: {
      hourKnown: false,
      source: "mixed",
      confidence: "low",
      patternTags: ["苏菲诗歌", "跨语言传播", "精神导师"],
    },
    bio: "波斯语苏菲诗歌代表人物。",
    situation: "迁徙至科尼亚后形成影响深远的精神与文学传统。",
    fitAssessment: "资料不足",
    analysisNotes: "出生细节争议大；只作宗教文学领域弱标签对照，不作文盲式格局断言。",
    classicalRefs: ["子平：生辰不确则不可强断"],
    sources: ["Britannica: Rumi"],
    counterexample: false,
  },
  {
    id: "joan-of-arc",
    name: "圣女贞德",
    nameEn: "Joan of Arc",
    gender: "female",
    era: "约 1412–1431",
    dynastyOrPeriod: "英法百年战争",
    country: "法国",
    region: "洛林",
    birthPlace: "栋雷米",
    socialClass: "农民/军事象征",
    field: ["军事", "宗教"],
    birth: {
      year: 1412,
      hour: null,
      calendar: "traditional-approx",
      precision: "uncertain",
      note: "出生约 1412，精确月日不确。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["底层跃升", "宗教异象叙事", "军事动员符号"],
      shiShenTendency: ["七杀", "正印", "伤官"],
    },
    bio: "百年战争中的法国军事与宗教象征人物。",
    situation: "以平民少女身份参与军政动员，后被处决，近世封圣。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：生辰粗糙却被后世极度命理化。战争、王朝合法性与宗教裁判所机制才是主叙事。",
    classicalRefs: ["三命通会：神异叙事不可替代史料"],
    sources: ["Britannica: Joan of Arc"],
    counterexample: true,
  },
  {
    id: "huang-daopo",
    name: "黄道婆",
    nameEn: "Huang Daopo",
    gender: "female",
    era: "约 1245–约 1330",
    dynastyOrPeriod: "宋元之际",
    country: "中国",
    region: "海南/上海松江",
    birthPlace: "松江乌泥泾（传统）",
    socialClass: "平民工匠",
    field: ["工程", "商业"],
    birth: {
      year: 1245,
      hour: null,
      calendar: "traditional-approx",
      precision: "uncertain",
      note: "生卒多为后世追述，精确日期不可考。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["棉纺织技术传播", "平民女性", "技艺改善民生"],
      shiShenTendency: ["食神", "偏财", "正印"],
    },
    bio: "传统记载中推动棉纺织技术传播的关键人物。",
    situation: "以工匠知识改善江南棉业，后世立祠纪念。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：几乎无可靠生辰，却在技术史上地位明确。破除‘必须有贵格才有社会贡献’的偏见。",
    classicalRefs: ["子平：技艺成就与官贵格局不可混同"],
    sources: ["地方志与科技史公开综述"],
    counterexample: true,
  },
  {
    id: "rosalind-franklin",
    name: "罗莎琳德·富兰克林",
    nameEn: "Rosalind Franklin",
    gender: "female",
    era: "1920–1958",
    dynastyOrPeriod: "20 世纪",
    country: "英国",
    region: "英格兰",
    birthPlace: "伦敦",
    socialClass: "学者",
    field: ["科学", "化学"],
    birth: {
      year: 1920,
      month: 7,
      day: 25,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["关键实验证据", "同行承认滞后", "性别结构障碍"],
    },
    bio: "DNA 结构研究中的关键实验科学家。",
    situation: "以 X 射线衍射等工作推动分子生物学，生前未获同等公共承认。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：科学贡献与‘名利格局’脱节。匹配时强调制度性承认偏差，反对用八字解释荣誉分配。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["Britannica: Rosalind Franklin"],
    counterexample: true,
  },
  {
    id: "ibn-battuta",
    name: "伊本·白图泰",
    nameEn: "Ibn Battuta",
    gender: "male",
    era: "1304–1368/1369",
    dynastyOrPeriod: "中世纪伊斯兰世界",
    country: "摩洛哥",
    region: "丹吉尔",
    birthPlace: "丹吉尔",
    socialClass: "学者/旅行家",
    field: ["史学", "宗教", "外交"],
    birth: {
      year: 1304,
      month: 2,
      day: 25,
      hour: null,
      calendar: "gregorian",
      precision: "uncertain",
      note: "传统记载生日；长途游记年代学仍有考证空间。",
    },
    chartTags: {
      hourKnown: false,
      source: "mixed",
      confidence: "low",
      patternTags: ["长途旅行", "跨文明记录", "司法与朝圣网络"],
    },
    bio: "中世纪著名穆斯林旅行家与游记作者。",
    situation: "游历亚非多地，留下重要地理与社会观察文本。",
    fitAssessment: "资料不足",
    analysisNotes: "旅行成就依赖商路、帝国驿站与宗教网络；生辰仅作弱特征。",
    classicalRefs: ["三命通会：驿马类神须谨慎比附"],
    sources: ["Britannica: Ibn Battuta"],
    counterexample: false,
  },
];

const raw = JSON.parse(fs.readFileSync(dataPath, "utf8"));
const existingIds = new Set(raw.map((x) => x.id));

const enriched = raw.map((fig) => {
  const meta = META[fig.id] || {
    gender: "unknown",
    country: "未知",
    region: undefined,
    birthPlace: undefined,
  };
  const birthCertainty =
    fig.birth.birthCertainty || precisionToCertainty(fig.birth.precision);
  return {
    ...fig,
    gender: fig.gender || meta.gender,
    country: fig.country || meta.country,
    region: fig.region || meta.region,
    birthPlace: fig.birthPlace || meta.birthPlace,
    birth: {
      ...fig.birth,
      birthCertainty,
    },
    fitDetail: fig.fitDetail || fitDetailFrom(fig),
    biorhythmNote:
      fig.biorhythmNote ||
      "经典 23/28/33 日节律仅作文化对照，不构成对该人物生平的科学解释。",
  };
});

const allExtras = [...EXTRA, ...EXTRA2].filter((x) => x && !x.skip);
for (const extra of allExtras) {
  if (existingIds.has(extra.id)) continue;
  existingIds.add(extra.id);
  enriched.push({
    ...extra,
    birth: {
      ...extra.birth,
      birthCertainty: precisionToCertainty(extra.birth.precision),
    },
    fitDetail: fitDetailFrom(extra),
    biorhythmNote:
      "经典 23/28/33 日节律仅作文化对照，不构成对该人物生平的科学解释。",
  });
}

fs.writeFileSync(dataPath, JSON.stringify(enriched, null, 2) + "\n", "utf8");

const genders = {};
const countries = {};
let female = 0;
let counter = 0;
for (const f of enriched) {
  genders[f.gender] = (genders[f.gender] || 0) + 1;
  countries[f.country] = (countries[f.country] || 0) + 1;
  if (f.gender === "female") female++;
  if (f.counterexample) counter++;
}
console.log("total", enriched.length);
console.log("female", female, "counterexamples", counter);
console.log("genders", genders);
console.log("countries", Object.keys(countries).length, Object.keys(countries).sort().join(" | "));
