/**
 * 第二批名人对照库扩展（多样性：性别、地域、领域、反例）。
 * 由 enrich-figures.mjs 合并；勿伪造时辰。
 */
export const EXTRA2 = [
  // ——— 中国女性 / 新省份 ———
  {
    id: "zhang-ailing",
    name: "张爱玲",
    nameEn: "Eileen Chang",
    gender: "female",
    era: "1920–1995",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "上海",
    birthPlace: "上海",
    socialClass: "都市文人",
    field: ["文学"],
    birth: {
      year: 1920,
      month: 9,
      day: 30,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行于年谱；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["都市书写", "战争与离散", "女性视角"],
    },
    bio: "20 世纪华文文学重要作家，以都市情感与乱世叙事著称。",
    situation: "上海成长，后赴港、美，作品长期影响现代汉语小说。",
    fitAssessment: "部分符合",
    analysisNotes:
      "伤官、桃花类附会常见。文学成就更应放在租界都市文化、出版市场与战争语境中理解。",
    classicalRefs: ["子平：才艺与情志标签不可史实化"],
    sources: ["张爱玲年谱通行材料", "公开传记年表"],
    counterexample: false,
  },
  {
    id: "bing-xin",
    name: "冰心",
    nameEn: "Bing Xin",
    gender: "female",
    era: "1900–1999",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "福建",
    birthPlace: "福州",
    socialClass: "知识分子",
    field: ["文学", "教育"],
    birth: {
      year: 1900,
      month: 10,
      day: 5,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "公历生日通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["儿童文学", "留学与译介", "长寿创作"],
    },
    bio: "现代散文与儿童文学代表作家之一。",
    situation: "以《寄小读者》等影响几代读者，并参与教育与公共文化。",
    fitAssessment: "部分符合",
    analysisNotes: "印食生秀易贴合，但新式教育与出版制度同样关键。",
    classicalRefs: ["滴天髓：才学须看际遇"],
    sources: ["冰心研究通行年表"],
    counterexample: false,
  },
  {
    id: "xiao-hong",
    name: "萧红",
    nameEn: "Xiao Hong",
    gender: "female",
    era: "1911–1942",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "黑龙江",
    birthPlace: "呼兰",
    socialClass: "左翼文人",
    field: ["文学"],
    birth: {
      year: 1911,
      month: 6,
      day: 1,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["东北书写", "流亡创作", "早逝"],
    },
    bio: "现代小说家，《呼兰河传》作者。",
    situation: "在战乱与贫困中坚持写作，英年早逝。",
    fitAssessment: "部分符合",
    analysisNotes: "疾厄、驿马附会常见；战乱流亡与出版网络更关键。",
    classicalRefs: ["三命通会：疾厄与才艺须分论"],
    sources: ["萧红年谱通行材料"],
    counterexample: false,
  },
  {
    id: "lin-huiyin",
    name: "林徽因",
    nameEn: "Lin Huiyin",
    gender: "female",
    era: "1904–1955",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "浙江/北京",
    birthPlace: "杭州",
    socialClass: "学者/建筑师",
    field: ["建筑", "文学", "学术"],
    birth: {
      year: 1904,
      month: 6,
      day: 10,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["建筑史调查", "跨界创作", "性别与专业壁垒"],
    },
    bio: "中国现代建筑史与文物保护重要参与者，亦为诗人。",
    situation: "与梁思成合作开展古建调查，战时辗转多地。",
    fitAssessment: "部分符合",
    analysisNotes: "才官双美叙事易套用。专业训练、家族资源与机构支持更关键。",
    classicalRefs: ["渊海子平：才官须看时势"],
    sources: ["林徽因研究通行年表"],
    counterexample: false,
  },
  {
    id: "wu-jianxiong",
    name: "吴健雄",
    nameEn: "Chien-Shiung Wu",
    gender: "female",
    era: "1912–1997",
    dynastyOrPeriod: "20 世纪",
    country: "中国/美国",
    region: "江苏",
    birthPlace: "太仓",
    socialClass: "学者",
    field: ["科学", "物理"],
    birth: {
      year: 1912,
      month: 5,
      day: 31,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["实验物理", "宇称不守恒验证", "荣誉滞后"],
    },
    bio: "核物理学家，以关键实验验证宇称不守恒闻名。",
    situation: "留学美国后长期从事实验物理，诺贝尔奖未授其本人常被讨论。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：重大科学贡献与最高奖项分配脱节。不可用‘名利格局’解释制度性承认偏差。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["Britannica: Chien-Shiung Wu", "公开科学史综述"],
    counterexample: true,
  },
  {
    id: "lin-qiaozhi",
    name: "林巧稚",
    nameEn: "Lin Qiaozhi",
    gender: "female",
    era: "1901–1983",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "福建",
    birthPlace: "厦门",
    socialClass: "医师",
    field: ["医学", "社会"],
    birth: {
      year: 1901,
      month: 12,
      day: 23,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["妇产科学", "终身行医", "公共服务"],
    },
    bio: "中国现代妇产科学奠基人之一。",
    situation: "长期在协和医院执业，推动妇幼健康事业。",
    fitAssessment: "部分符合",
    analysisNotes: "印星、食神类比易贴合；现代医学教育与医院制度才是主因。",
    classicalRefs: ["子平：技艺与官贵不可混同"],
    sources: ["公开人物传记与医学史综述"],
    counterexample: false,
  },
  {
    id: "deng-yingchao",
    name: "邓颖超",
    nameEn: "Deng Yingchao",
    gender: "female",
    era: "1904–1992",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "河南",
    birthPlace: "光山",
    socialClass: "政治家",
    field: ["政治", "社会运动"],
    birth: {
      year: 1904,
      month: 2,
      day: 4,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["妇女运动", "长期从政", "统一战线工作"],
    },
    bio: "中国近现代政治与妇女运动重要人物。",
    situation: "长期参与革命与建国后国家事务，推动妇女权益议题。",
    fitAssessment: "部分符合",
    analysisNotes: "女命官星叙事易事后附会。组织网络与历史进程更关键。",
    classicalRefs: ["三命通会：女命官星说须历史化"],
    sources: ["公开人物年表"],
    counterexample: false,
  },
  {
    id: "xiang-jingyu",
    name: "向警予",
    nameEn: "Xiang Jingyu",
    gender: "female",
    era: "1895–1928",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "湖南",
    birthPlace: "溆浦",
    socialClass: "革命者",
    field: ["政治", "社会运动"],
    birth: {
      year: 1895,
      month: 9,
      day: 4,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行于史料；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["早期妇女运动", "革命牺牲"],
    },
    bio: "中国早期妇女运动与共产党重要人物。",
    situation: "投身工人与妇女运动，被捕后遇害。",
    fitAssessment: "部分符合",
    analysisNotes: "烈性、杀星附会常见。政治镇压与运动组织史不可简化为格局。",
    classicalRefs: ["子平：官杀与革命史不可等同"],
    sources: ["公开革命史人物年表"],
    counterexample: false,
  },
  {
    id: "he-xiangning",
    name: "何香凝",
    nameEn: "He Xiangning",
    gender: "female",
    era: "1878–1972",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "广东",
    birthPlace: "南海",
    socialClass: "政治家/艺术家",
    field: ["政治", "艺术", "社会运动"],
    birth: {
      year: 1878,
      month: 6,
      day: 27,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["同盟会网络", "书画创作", "妇女与民权"],
    },
    bio: "民主革命家、画家，廖仲恺夫人。",
    situation: "长期参与革命与建国后政治文化活动。",
    fitAssessment: "部分符合",
    analysisNotes: "才官并行叙事易贴合；华侨网络与党派政治更关键。",
    classicalRefs: ["渊海子平：才官清浊须分看"],
    sources: ["公开人物传记"],
    counterexample: false,
  },
  {
    id: "song-meiling",
    name: "宋美龄",
    nameEn: "Soong Mei-ling",
    gender: "female",
    era: "约 1898–2003",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "上海/广东关联",
    birthPlace: "上海一带（记载有异）",
    socialClass: "政治人物",
    field: ["政治", "外交"],
    birth: {
      year: 1898,
      month: 3,
      day: 5,
      hour: null,
      calendar: "gregorian",
      precision: "uncertain",
      note: "生年有 1897/1898 等异说，取通行纪念日期，置信偏低；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "mixed",
      confidence: "low",
      patternTags: ["战时外交", "第一夫人角色", "生年争议"],
    },
    bio: "近现代中国政治舞台重要女性人物。",
    situation: "以公共演说与外交活动影响抗战时期国际舆论。",
    fitAssessment: "资料不足",
    analysisNotes: "生年争议本身即提醒：不可用单一生日硬排‘国运格局’。",
    classicalRefs: ["子平：生辰不确则不可强断"],
    sources: ["公开传记与年谱考证概述"],
    counterexample: false,
  },
  {
    id: "teresa-teng",
    name: "邓丽君",
    nameEn: "Teresa Teng",
    gender: "female",
    era: "1953–1995",
    dynastyOrPeriod: "当代东亚",
    country: "中国",
    region: "台湾",
    birthPlace: "云林",
    socialClass: "流行歌手",
    field: ["艺术", "音乐"],
    birth: {
      year: 1953,
      month: 1,
      day: 29,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["华语流行", "跨海峡传播", "大众文化"],
    },
    bio: "20 世纪华语流行音乐标志性歌手。",
    situation: "唱片与媒体工业推动其歌曲在两岸三地广泛传唱。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤生秀易套用。录音工业、冷战语境与大众口味更关键。",
    classicalRefs: ["子平：才艺成就须看时势"],
    sources: ["公开艺人传记年表"],
    counterexample: false,
  },
  {
    id: "yuan-longping",
    name: "袁隆平",
    nameEn: "Yuan Longping",
    gender: "male",
    era: "1930–2021",
    dynastyOrPeriod: "当代中国",
    country: "中国",
    region: "北京/湖南工作",
    birthPlace: "北京",
    socialClass: "农学家",
    field: ["科学", "农业", "工程"],
    birth: {
      year: 1930,
      month: 9,
      day: 7,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["杂交水稻", "粮食安全", "田野实验"],
    },
    bio: "杂交水稻研究开创者之一。",
    situation: "长期在湖南等地从事育种，影响全球粮食生产讨论。",
    fitAssessment: "部分符合",
    analysisNotes: "偏财、食伤生财叙事易套用。国家农业科研体系与田间试验更关键。",
    classicalRefs: ["滴天髓：事功须看际遇"],
    sources: ["公开人物传记与农业史综述"],
    counterexample: false,
  },
  {
    id: "qian-xuesen",
    name: "钱学森",
    nameEn: "Qian Xuesen",
    gender: "male",
    era: "1911–2009",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "浙江",
    birthPlace: "上海（籍贯杭州）",
    socialClass: "科学家",
    field: ["科学", "工程", "军事"],
    birth: {
      year: 1911,
      month: 12,
      day: 11,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["航天工程", "归国服务", "系统科学"],
    },
    bio: "空气动力学与中国航天事业关键科学家。",
    situation: "留学美国后归国，参与导弹与航天工程体系建设。",
    fitAssessment: "部分符合",
    analysisNotes: "官杀、印星类比常见。冷战科技竞争与国家动员才是主叙事。",
    classicalRefs: ["渊海子平：官星与事功须分看"],
    sources: ["公开人物年表"],
    counterexample: false,
  },
  {
    id: "hua-luogeng",
    name: "华罗庚",
    nameEn: "Hua Luogeng",
    gender: "male",
    era: "1910–1985",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "江苏",
    birthPlace: "金坛",
    socialClass: "学者",
    field: ["科学", "数学", "教育"],
    birth: {
      year: 1910,
      month: 11,
      day: 12,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["自学成才叙事", "数论与应用", "科普推广"],
    },
    bio: "中国现代数学重要人物，推动优选法普及。",
    situation: "从基层成长为国际知名数学家，并参与应用数学推广。",
    fitAssessment: "部分符合",
    analysisNotes:
      "反确认偏误：自学叙事常被命理化为‘印星得力’； mentorship、期刊网络与时代需求同样关键。",
    classicalRefs: ["滴天髓：才学须综合得令得地"],
    sources: ["公开数学史与人物传记"],
    counterexample: false,
  },
  {
    id: "yang-zhenning",
    name: "杨振宁",
    nameEn: "Chen-Ning Yang",
    gender: "male",
    era: "1922–",
    dynastyOrPeriod: "当代",
    country: "中国/美国",
    region: "安徽",
    birthPlace: "合肥",
    socialClass: "学者",
    field: ["科学", "物理"],
    birth: {
      year: 1922,
      month: 10,
      day: 1,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["理论物理", "诺贝尔奖", "中美学术网络"],
    },
    bio: "理论物理学家，杨–米尔斯规范场等贡献卓著。",
    situation: "在西南联大与海外学术体系中成长，后长期影响华人科学界。",
    fitAssessment: "部分符合",
    analysisNotes: "学人贵格附会易过度。研究共同体与冷战学术体制更关键。",
    classicalRefs: ["子平：名位须看时势"],
    sources: ["Nobel Prize biography / 公开年表"],
    counterexample: false,
  },
  {
    id: "lao-she",
    name: "老舍",
    nameEn: "Lao She",
    gender: "male",
    era: "1899–1966",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "北京",
    birthPlace: "北京",
    socialClass: "文人",
    field: ["文学", "戏剧"],
    birth: {
      year: 1899,
      month: 2,
      day: 3,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["市民文学", "话剧创作", "政治运动冲击"],
    },
    bio: "现代小说与戏剧家，《骆驼祥子》《茶馆》作者。",
    situation: "描写北京市民生活，文革中去世。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：文学声望与晚年遭遇不能用单一‘吉凶格局’贯通。政治运动结构压力是关键。",
    classicalRefs: ["三命通会：岁运与人事并参"],
    sources: ["老舍年谱通行材料"],
    counterexample: true,
  },
  {
    id: "ba-jin",
    name: "巴金",
    nameEn: "Ba Jin",
    gender: "male",
    era: "1904–2005",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "四川",
    birthPlace: "成都",
    socialClass: "文人",
    field: ["文学"],
    birth: {
      year: 1904,
      month: 11,
      day: 25,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["激流三部曲", "长寿作家", "反思文革"],
    },
    bio: "现代文学巨匠，《家》等作品影响深远。",
    situation: "从无政府主义青年到文坛领袖，晚年推动历史反思。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤、印星叙事易贴合；出版制度与政治气候变化更关键。",
    classicalRefs: ["滴天髓：文才须看际遇"],
    sources: ["巴金年谱通行材料"],
    counterexample: false,
  },
  {
    id: "zhang-xueliang",
    name: "张学良",
    nameEn: "Zhang Xueliang",
    gender: "male",
    era: "1901–2001",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "辽宁",
    birthPlace: "海城一带",
    socialClass: "军人/政治人物",
    field: ["军事", "政治"],
    birth: {
      year: 1901,
      month: 6,
      day: 3,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["东北军", "西安事变", "长期软禁"],
    },
    bio: "东北军领袖，西安事变关键人物。",
    situation: "发动兵谏后遭长期软禁，晚年移居夏威夷。",
    fitAssessment: "部分符合",
    analysisNotes: "七杀、驿马类附会极多。军阀政治与国际形势才是主因。",
    classicalRefs: ["子平：官杀战勿直接史实化"],
    sources: ["公开近代史人物年表"],
    counterexample: false,
  },
  {
    id: "zhan-tianyou",
    name: "詹天佑",
    nameEn: "Zhan Tianyou",
    gender: "male",
    era: "1861–1919",
    dynastyOrPeriod: "晚清民初",
    country: "中国",
    region: "广东",
    birthPlace: "南海",
    socialClass: "工程师",
    field: ["工程", "教育"],
    birth: {
      year: 1861,
      month: 4,
      day: 26,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["铁路工程", "留美幼童", "技术自立叙事"],
    },
    bio: "京张铁路总工程师，中国近代工程象征人物。",
    situation: "以工程实践推动铁路建设与技术教育。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤生财易套用。留美教育与清末新政技术引进更关键。",
    classicalRefs: ["子平：技艺与财官须分论"],
    sources: ["公开工程史人物传记"],
    counterexample: false,
  },
  {
    id: "nie-er",
    name: "聂耳",
    nameEn: "Nie Er",
    gender: "male",
    era: "1912–1935",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "云南",
    birthPlace: "昆明",
    socialClass: "音乐家",
    field: ["艺术", "音乐", "社会运动"],
    birth: {
      year: 1912,
      month: 2,
      day: 15,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["救亡歌曲", "早逝", "国歌旋律关联"],
    },
    bio: "作曲家，《义勇军进行曲》曲作者。",
    situation: "左翼音乐运动中崭露头角，溺水早逝。",
    fitAssessment: "部分符合",
    analysisNotes: "短命才名叙事易命理化。救亡文化动员与大众传媒更关键。",
    classicalRefs: ["三命通会：寿夭与事功须分看"],
    sources: ["公开人物年表"],
    counterexample: false,
  },
  {
    id: "jin-yong",
    name: "金庸",
    nameEn: "Jin Yong",
    gender: "male",
    era: "1924–2018",
    dynastyOrPeriod: "当代",
    country: "中国",
    region: "浙江/香港",
    birthPlace: "海宁",
    socialClass: "报人/小说家",
    field: ["文学", "新闻"],
    birth: {
      year: 1924,
      month: 3,
      day: 10,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["武侠小说", "报业", "大众文化"],
    },
    bio: "新派武侠小说代表作家，亦为报人。",
    situation: "在香港报业与连载市场中建立巨大文化影响。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤生财叙事易套用。连载制度与冷战港岛传媒生态更关键。",
    classicalRefs: ["子平：才财相生标签勿神话化"],
    sources: ["公开人物传记"],
    counterexample: false,
  },
  {
    id: "ouyang-xiu",
    name: "欧阳修",
    nameEn: "Ouyang Xiu",
    gender: "male",
    era: "1007–1072",
    dynastyOrPeriod: "北宋",
    country: "中国",
    region: "江西",
    birthPlace: "永丰一带（传统）",
    socialClass: "士大夫",
    field: ["文学", "政治", "史学"],
    birth: {
      year: 1007,
      hour: null,
      calendar: "traditional-approx",
      precision: "year-only",
      note: "生年传统记载较稳，精确月日与时辰不足以为高置信排盘。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["古文运动", "史官与谏议", "江西士大夫"],
      shiShenTendency: ["正印", "食神", "正官"],
    },
    bio: "北宋文学家、史学家、政治家。",
    situation: "推动古文与史学编纂，历任要职亦遭贬谪。",
    fitAssessment: "资料不足",
    analysisNotes: "年仅可考时只作弱标签对照，禁止伪造日时。",
    classicalRefs: ["渊海子平：时辰不明难定全局"],
    sources: ["宋史与文学史公开综述"],
    counterexample: false,
  },
  {
    id: "wang-anshi",
    name: "王安石",
    nameEn: "Wang Anshi",
    gender: "male",
    era: "1021–1086",
    dynastyOrPeriod: "北宋",
    country: "中国",
    region: "江西",
    birthPlace: "临川",
    socialClass: "士大夫",
    field: ["政治", "文学", "思想"],
    birth: {
      year: 1021,
      hour: null,
      calendar: "traditional-approx",
      precision: "year-only",
      note: "生年传统记载；精确月日时辰不足。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["变法改革", "争议巨大", "江西临川"],
      shiShenTendency: ["七杀", "伤官", "正印"],
    },
    bio: "北宋政治家，熙宁变法核心人物。",
    situation: "主导新法引发持久党争，身后评价两极。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：改革成败被后世极度命理化。财政、边防与官僚政治才是主因。",
    classicalRefs: ["子平：官杀战勿直接史实化"],
    sources: ["宋史公开综述"],
    counterexample: true,
  },
  {
    id: "wen-tianxiang",
    name: "文天祥",
    nameEn: "Wen Tianxiang",
    gender: "male",
    era: "1236–1283",
    dynastyOrPeriod: "南宋",
    country: "中国",
    region: "江西",
    birthPlace: "吉州庐陵",
    socialClass: "士大夫/忠烈象征",
    field: ["政治", "军事", "文学"],
    birth: {
      year: 1236,
      month: 6,
      day: 6,
      hour: null,
      calendar: "gregorian",
      precision: "uncertain",
      note: "传统纪年换算后的常见日期；历法细节存研究空间，时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "mixed",
      confidence: "low",
      patternTags: ["抗元", "正气歌", "忠烈叙事"],
    },
    bio: "南宋末抗元领袖与诗文象征人物。",
    situation: "组织抵抗后被俘就义，成为后世气节符号。",
    fitAssessment: "部分符合",
    analysisNotes: "七杀、正官忠烈附会极常见。王朝崩解与军事局势不可简化。",
    classicalRefs: ["滴天髓：忠奸标签须历史化"],
    sources: ["宋史与文学史公开综述"],
    counterexample: false,
  },
  {
    id: "bao-zheng",
    name: "包拯",
    nameEn: "Bao Zheng",
    gender: "male",
    era: "999–1062",
    dynastyOrPeriod: "北宋",
    country: "中国",
    region: "安徽",
    birthPlace: "合肥一带",
    socialClass: "官僚",
    field: ["政治", "法律"],
    birth: {
      year: 999,
      hour: null,
      calendar: "traditional-approx",
      precision: "year-only",
      note: "生年传统记载；精确月日时辰不足。后世戏曲形象不可当作生辰证据。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["清官象征", "司法叙事", "戏曲层累造神"],
      shiShenTendency: ["正官", "七杀", "正印"],
    },
    bio: "北宋官员，后世被塑造为清官象征。",
    situation: "历史政绩与戏曲传奇长期叠加，形象远超可考细节。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：公众‘包青天’形象远厚于可考生辰。文化符号化不等于命理可验证。",
    classicalRefs: ["三命通会：神异叙事不可替代史料"],
    sources: ["宋史公开综述 / 清官文化研究概述"],
    counterexample: true,
  },
  {
    id: "cai-yuanpei",
    name: "蔡元培",
    nameEn: "Cai Yuanpei",
    gender: "male",
    era: "1868–1940",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "浙江",
    birthPlace: "绍兴",
    socialClass: "教育家",
    field: ["教育", "思想", "政治"],
    birth: {
      year: 1868,
      month: 1,
      day: 11,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["北大改革", "兼容并包", "美育主张"],
    },
    bio: "近代教育家，北京大学改革关键人物。",
    situation: "推动大学制度与学术自由理念，影响新文化运动生态。",
    fitAssessment: "部分符合",
    analysisNotes: "印星文昌附会常见。大学制度移植与政治庇护更关键。",
    classicalRefs: ["滴天髓：文星须看际遇"],
    sources: ["蔡元培年谱通行材料"],
    counterexample: false,
  },
  {
    id: "hu-shi",
    name: "胡适",
    nameEn: "Hu Shi",
    gender: "male",
    era: "1891–1962",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "安徽",
    birthPlace: "绩溪",
    socialClass: "知识分子",
    field: ["思想", "文学", "教育"],
    birth: {
      year: 1891,
      month: 12,
      day: 17,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["白话文运动", "实验主义", "公共论争"],
    },
    bio: "新文化运动代表人物之一，学者与公共知识分子。",
    situation: "推动白话文学与学术方法讨论，后在两岸学术政治中角色复杂。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官见官式‘叛逆革新’附会常见。留学网络与大学体制更关键。",
    classicalRefs: ["子平：伤官见官勿史实化"],
    sources: ["胡适日记与年谱公开材料"],
    counterexample: false,
  },
  {
    id: "fei-xiaotong",
    name: "费孝通",
    nameEn: "Fei Xiaotong",
    gender: "male",
    era: "1910–2005",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "江苏",
    birthPlace: "吴江",
    socialClass: "学者",
    field: ["学术", "社会学", "教育"],
    birth: {
      year: 1910,
      month: 11,
      day: 2,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["乡土中国", "田野调查", "民族研究"],
    },
    bio: "中国社会学与人类学重要奠基人之一。",
    situation: "以乡土调查影响社会科学，政治运动中亦遭冲击后复出。",
    fitAssessment: "部分符合",
    analysisNotes: "印食学术格局易套用。学科建制与国家民族政策需求更关键。",
    classicalRefs: ["滴天髓：才学须看时势"],
    sources: ["公开学术人物年表"],
    counterexample: false,
  },
  {
    id: "puyi",
    name: "溥仪",
    nameEn: "Puyi",
    gender: "male",
    era: "1906–1967",
    dynastyOrPeriod: "清末至当代",
    country: "中国",
    region: "北京",
    birthPlace: "北京",
    socialClass: "帝王/平民转化",
    field: ["政治"],
    birth: {
      year: 1906,
      month: 2,
      day: 7,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["末代皇帝", "身份剧变", "改造叙事"],
    },
    bio: "清朝末代皇帝，经历逊位、伪满与改造。",
    situation: "从帝制顶点跌落为普通公民，生平常被命理市场消费。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：‘真龙天子’到阶下囚的落差最易被八字话术收编。帝国崩溃与国际政治才是主因。",
    classicalRefs: ["滴天髓：君相造命说须历史化"],
    sources: ["溥仪自传与近代史公开材料"],
    counterexample: true,
  },

  // ——— 国际女性 / 新国家 ———
  {
    id: "jane-austen",
    name: "简·奥斯汀",
    nameEn: "Jane Austen",
    gender: "female",
    era: "1775–1817",
    dynastyOrPeriod: "乔治王时代英国",
    country: "英国",
    region: "英格兰",
    birthPlace: "斯蒂文顿",
    socialClass: "士绅女性作家",
    field: ["文学"],
    birth: {
      year: 1775,
      month: 12,
      day: 16,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["小说革新", "匿名出版", "后世经典化"],
    },
    bio: "英语小说经典作家，《傲慢与偏见》作者。",
    situation: "生前声名有限，后世成为世界文学经典。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤生秀易套用。出版匿名制与中产阶级阅读市场更关键。",
    classicalRefs: ["子平：才艺与名位须分看"],
    sources: ["Britannica: Jane Austen"],
    counterexample: false,
  },
  {
    id: "virginia-woolf",
    name: "弗吉尼亚·伍尔夫",
    nameEn: "Virginia Woolf",
    gender: "female",
    era: "1882–1941",
    dynastyOrPeriod: "20 世纪英国",
    country: "英国",
    region: "英格兰",
    birthPlace: "伦敦",
    socialClass: "现代主义文人",
    field: ["文学", "思想"],
    birth: {
      year: 1882,
      month: 1,
      day: 25,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["意识流", "女权批评", "精神健康议题"],
    },
    bio: "现代主义文学与女性主义思想关键人物。",
    situation: "布卢姆斯伯里圈子中创作，后自杀身亡。",
    fitAssessment: "部分符合",
    analysisNotes: "疾厄与才情附会常见。精神健康与出版实验不可简化为格局。",
    classicalRefs: ["三命通会：疾厄与才艺须分论"],
    sources: ["Britannica: Virginia Woolf"],
    counterexample: false,
  },
  {
    id: "emmy-noether",
    name: "埃米·诺特",
    nameEn: "Emmy Noether",
    gender: "female",
    era: "1882–1935",
    dynastyOrPeriod: "20 世纪",
    country: "德国",
    region: "巴伐利亚",
    birthPlace: "埃尔朗根",
    socialClass: "学者",
    field: ["科学", "数学"],
    birth: {
      year: 1882,
      month: 3,
      day: 23,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["抽象代数", "诺特定理", "性别壁垒"],
    },
    bio: "抽象代数与理论物理数学基础的关键贡献者。",
    situation: "长期缺乏正式教职，仍深刻影响现代数学。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：学术贡献与职位/荣誉严重不对称。制度性排斥不能用命理解释。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["Britannica: Emmy Noether"],
    counterexample: true,
  },
  {
    id: "rachel-carson",
    name: "蕾切尔·卡森",
    nameEn: "Rachel Carson",
    gender: "female",
    era: "1907–1964",
    dynastyOrPeriod: "20 世纪美国",
    country: "美国",
    region: "宾夕法尼亚",
    birthPlace: "斯普林代尔",
    socialClass: "科学家/作家",
    field: ["科学", "社会运动", "文学"],
    birth: {
      year: 1907,
      month: 5,
      day: 27,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["环保启蒙", "科普写作", "公共政策影响"],
    },
    bio: "《寂静的春天》作者，现代环保运动关键推动者。",
    situation: "以科学写作挑战农药工业叙事，影响政策讨论。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官见官式‘对抗权威’附会常见。科学传播与公民运动更关键。",
    classicalRefs: ["子平：伤官见官勿史实化"],
    sources: ["Britannica: Rachel Carson"],
    counterexample: false,
  },
  {
    id: "rosa-parks",
    name: "罗莎·帕克斯",
    nameEn: "Rosa Parks",
    gender: "female",
    era: "1913–2005",
    dynastyOrPeriod: "20 世纪美国",
    country: "美国",
    region: "亚拉巴马",
    birthPlace: "塔斯基吉",
    socialClass: "民权活动家",
    field: ["社会运动", "政治"],
    birth: {
      year: 1913,
      month: 2,
      day: 4,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["民权运动", "抵制巴士", "组织准备"],
    },
    bio: "美国民权运动象征人物。",
    situation: "蒙哥马利巴士抵制的关键节点人物，背后有长期组织工作。",
    fitAssessment: "部分符合",
    analysisNotes:
      "‘一人改变历史’的命理神话需警惕。民权组织网络与法律策略更关键。",
    classicalRefs: ["三命通会：岁运与人事并参"],
    sources: ["Britannica: Rosa Parks"],
    counterexample: false,
  },
  {
    id: "margaret-thatcher",
    name: "玛格丽特·撒切尔",
    nameEn: "Margaret Thatcher",
    gender: "female",
    era: "1925–2013",
    dynastyOrPeriod: "20 世纪英国",
    country: "英国",
    region: "英格兰",
    birthPlace: "格兰瑟姆",
    socialClass: "政治家",
    field: ["政治"],
    birth: {
      year: 1925,
      month: 10,
      day: 13,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["首位女首相", "新自由主义政策", "争议巨大"],
    },
    bio: "英国首位女首相。",
    situation: "推动市场化改革，国内外评价严重两极。",
    fitAssessment: "部分符合",
    analysisNotes: "女帝/女官格局附会常见。政党重组与冷战末期经济结构更关键。",
    classicalRefs: ["三命通会：女命官星说须历史化"],
    sources: ["Britannica: Margaret Thatcher"],
    counterexample: false,
  },
  {
    id: "indira-gandhi",
    name: "英迪拉·甘地",
    nameEn: "Indira Gandhi",
    gender: "female",
    era: "1917–1984",
    dynastyOrPeriod: "20 世纪印度",
    country: "印度",
    region: "北方邦",
    birthPlace: "阿拉哈巴德",
    socialClass: "政治家",
    field: ["政治"],
    birth: {
      year: 1917,
      month: 11,
      day: 19,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["女总理", "紧急状态争议", "遇刺"],
    },
    bio: "印度首位女总理。",
    situation: "长期主导国大党政治，任内争议与遇刺均影响深远。",
    fitAssessment: "部分符合",
    analysisNotes: "权柄格局附会极多。家族政党机器与南亚地缘政治更关键。",
    classicalRefs: ["渊海子平：官星与权位须分看"],
    sources: ["Britannica: Indira Gandhi"],
    counterexample: false,
  },
  {
    id: "golda-meir",
    name: "果尔达·梅厄",
    nameEn: "Golda Meir",
    gender: "female",
    era: "1898–1978",
    dynastyOrPeriod: "20 世纪",
    country: "以色列",
    region: "基辅出生/以色列执政",
    birthPlace: "基辅",
    socialClass: "政治家",
    field: ["政治", "外交"],
    birth: {
      year: 1898,
      month: 5,
      day: 3,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["女总理", "建国一代", "战争决策争议"],
    },
    bio: "以色列首位女总理。",
    situation: "从劳工锡安主义活动家成长为国家领导人。",
    fitAssessment: "部分符合",
    analysisNotes: "女命官星叙事易套用。移民网络与中东战争结构更关键。",
    classicalRefs: ["三命通会：女命官星说须历史化"],
    sources: ["Britannica: Golda Meir"],
    counterexample: false,
  },
  {
    id: "wangari-maathai",
    name: "旺加里·马塔伊",
    nameEn: "Wangari Maathai",
    gender: "female",
    era: "1940–2011",
    dynastyOrPeriod: "当代非洲",
    country: "肯尼亚",
    region: "中央省",
    birthPlace: "尼耶里一带",
    socialClass: "学者/活动家",
    field: ["社会运动", "科学", "政治"],
    birth: {
      year: 1940,
      month: 4,
      day: 1,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["绿带运动", "环保与民主", "诺贝尔和平奖"],
    },
    bio: "肯尼亚环保与民主活动家，诺贝尔和平奖得主。",
    situation: "以植树与公民行动连接生态与政治权利。",
    fitAssessment: "部分符合",
    analysisNotes: "印食、伤官对抗叙事易贴合。基层组织与国际 NGO 网络更关键。",
    classicalRefs: ["子平：事功须看时势"],
    sources: ["Nobel Prize biography: Wangari Maathai"],
    counterexample: false,
  },
  {
    id: "eva-peron",
    name: "埃娃·庇隆",
    nameEn: "Eva Perón",
    gender: "female",
    era: "1919–1952",
    dynastyOrPeriod: "20 世纪拉美",
    country: "阿根廷",
    region: "布宜诺斯艾利斯省",
    birthPlace: "洛斯托尔多斯",
    socialClass: "政治人物/演员出身",
    field: ["政治", "社会运动"],
    birth: {
      year: 1919,
      month: 5,
      day: 7,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["民粹动员", "妇女选举权", "早逝符号化"],
    },
    bio: "阿根廷第一夫人与政治动员象征。",
    situation: "推动社会福利与妇女参政叙事，去世后成为文化偶像。",
    fitAssessment: "部分符合",
    analysisNotes: "桃花、偏财、官星附会极多。传媒政治与工会结构更关键。",
    classicalRefs: ["三命通会：名气与权柄须分论"],
    sources: ["Britannica: Eva Perón"],
    counterexample: false,
  },
  {
    id: "mother-teresa",
    name: "特蕾莎修女",
    nameEn: "Mother Teresa",
    gender: "female",
    era: "1910–1997",
    dynastyOrPeriod: "20 世纪",
    country: "阿尔巴尼亚/印度",
    region: "斯科普里出生/加尔各答工作",
    birthPlace: "斯科普里",
    socialClass: "宗教慈善家",
    field: ["宗教", "慈善", "社会"],
    birth: {
      year: 1910,
      month: 8,
      day: 26,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["慈善机构", "争议与圣化并存", "跨国宗教网络"],
    },
    bio: "天主教慈善工作代表人物，诺贝尔和平奖得主。",
    situation: "在加尔各答等地开展济贫，同时引发医疗与资金使用争议。",
    fitAssessment: "部分符合",
    analysisNotes:
      "印星、善神叙事易神话化。教育用途须并陈批评文献，反对命理圣化。",
    classicalRefs: ["滴天髓：名实须对勘"],
    sources: ["Nobel Prize biography / 公开批评与传记综述"],
    counterexample: false,
  },
  {
    id: "simone-de-beauvoir",
    name: "西蒙娜·德·波伏瓦",
    nameEn: "Simone de Beauvoir",
    gender: "female",
    era: "1908–1986",
    dynastyOrPeriod: "20 世纪法国",
    country: "法国",
    region: "巴黎",
    birthPlace: "巴黎",
    socialClass: "知识分子",
    field: ["思想", "文学", "社会运动"],
    birth: {
      year: 1908,
      month: 1,
      day: 9,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["存在主义", "第二性", "女权理论"],
    },
    bio: "法国存在主义哲学家与女权理论家。",
    situation: "以《第二性》深刻影响当代性别研究与社会运动。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官、印星论辩叙事易贴合。巴黎知识场域与出版制度更关键。",
    classicalRefs: ["子平：才学与论争标签勿神话化"],
    sources: ["Britannica: Simone de Beauvoir"],
    counterexample: false,
  },
  {
    id: "frida-kahlo-skip",
    skip: true,
  },
  {
    id: "malala",
    name: "马拉拉·优素福扎伊",
    nameEn: "Malala Yousafzai",
    gender: "female",
    era: "1997–",
    dynastyOrPeriod: "当代",
    country: "巴基斯坦",
    region: "开伯尔-普赫图赫瓦",
    birthPlace: "明戈拉",
    socialClass: "教育与人权活动家",
    field: ["社会运动", "教育", "政治"],
    birth: {
      year: 1997,
      month: 7,
      day: 12,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["女童教育", "国际倡导", "诺贝尔和平奖"],
    },
    bio: "教育与人权活动家，最年轻诺贝尔和平奖得主之一。",
    situation: "因倡导女童教育遭袭击后成为全球象征。",
    fitAssessment: "部分符合",
    analysisNotes: "七杀、印星劫后成名附会常见。媒体政治与国际人权机制更关键。",
    classicalRefs: ["三命通会：岁运与人事并参"],
    sources: ["Nobel Prize biography: Malala Yousafzai"],
    counterexample: false,
  },
  {
    id: "yosano-akiko",
    name: "与谢野晶子",
    nameEn: "Yosano Akiko",
    gender: "female",
    era: "1878–1942",
    dynastyOrPeriod: "日本近代",
    country: "日本",
    region: "大阪",
    birthPlace: "堺",
    socialClass: "诗人/评论家",
    field: ["文学", "社会运动"],
    birth: {
      year: 1878,
      month: 12,
      day: 7,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["短歌革新", "反战诗", "女性解放言论"],
    },
    bio: "日本近代诗人，以大胆短歌与反战诗闻名。",
    situation: "在明治大正言论空间中挑战性别与战争规范。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官见官附会常见。报刊资本主义与女权思潮更关键。",
    classicalRefs: ["子平：伤官见官勿史实化"],
    sources: ["日本近代文学研究通行概述"],
    counterexample: false,
  },

  // ——— 国际男性：科学、艺术、政治、体育、宗教 ———
  {
    id: "mozart",
    name: "沃尔夫冈·阿马德乌斯·莫扎特",
    nameEn: "Wolfgang Amadeus Mozart",
    gender: "male",
    era: "1756–1791",
    dynastyOrPeriod: "古典主义欧洲",
    country: "奥地利",
    region: "萨尔茨堡",
    birthPlace: "萨尔茨堡",
    socialClass: "宫廷/城市音乐家",
    field: ["艺术", "音乐"],
    birth: {
      year: 1756,
      month: 1,
      day: 27,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知（虽有受洗记录，本库不采信单一时辰断语）。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["神童叙事", "歌剧与交响", "Patronage 体制"],
    },
    bio: "古典主义音乐巅峰人物之一。",
    situation: "在宫廷赞助与城市音乐市场间求生，英年早逝。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤、天才格局附会极多。赞助人制度与音乐教育网络更关键。",
    classicalRefs: ["子平：才艺与寿夭须分看"],
    sources: ["Britannica: Wolfgang Amadeus Mozart"],
    counterexample: false,
  },
  {
    id: "leonardo",
    name: "列奥纳多·达·芬奇",
    nameEn: "Leonardo da Vinci",
    gender: "male",
    era: "1452–1519",
    dynastyOrPeriod: "文艺复兴",
    country: "意大利",
    region: "托斯卡纳",
    birthPlace: "芬奇镇附近",
    socialClass: "工匠/宫廷艺术家",
    field: ["艺术", "工程", "科学"],
    birth: {
      year: 1452,
      month: 4,
      day: 15,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "传统记载生日；时辰有传说但不采信为可靠字段。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["跨界博学", "赞助人网络", "未完成手稿"],
    },
    bio: "文艺复兴通才，画家与工程师。",
    situation: "在佛罗伦萨、米兰等地宫廷与作坊体系中创作。",
    fitAssessment: "部分符合",
    analysisNotes: "通才格局附会常见。作坊训练与城邦Patronage 更关键。",
    classicalRefs: ["滴天髓：才学须看际遇"],
    sources: ["Britannica: Leonardo da Vinci"],
    counterexample: false,
  },
  {
    id: "galileo",
    name: "伽利略·伽利莱",
    nameEn: "Galileo Galilei",
    gender: "male",
    era: "1564–1642",
    dynastyOrPeriod: "科学革命",
    country: "意大利",
    region: "托斯卡纳",
    birthPlace: "比萨",
    socialClass: "学者",
    field: ["科学", "物理", "天文"],
    birth: {
      year: 1564,
      month: 2,
      day: 15,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["望远镜观测", "与教廷冲突", "力学奠基"],
    },
    bio: "近代科学革命关键人物。",
    situation: "观测与力学研究挑战亚里士多德—托勒密框架，遭宗教审判。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官见官附会极常见。印刷、宫廷科学与教会政治更关键。",
    classicalRefs: ["子平：伤官见官勿史实化"],
    sources: ["Britannica: Galileo"],
    counterexample: false,
  },
  {
    id: "marie-sklodowska-already",
    skip: true,
  },
  {
    id: "pasteur",
    name: "路易·巴斯德",
    nameEn: "Louis Pasteur",
    gender: "male",
    era: "1822–1895",
    dynastyOrPeriod: "19 世纪法国",
    country: "法国",
    region: "汝拉",
    birthPlace: "多勒",
    socialClass: "学者",
    field: ["科学", "医学", "化学"],
    birth: {
      year: 1822,
      month: 12,
      day: 27,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["微生物学", "疫苗与消毒", "公共卫生"],
    },
    bio: "微生物学与疫苗研究奠基者之一。",
    situation: "实验室发现转化为公共卫生与工业实践。",
    fitAssessment: "部分符合",
    analysisNotes: "印食、偏财济世叙事易套用。国家实验室与产业需求更关键。",
    classicalRefs: ["滴天髓：事功须看际遇"],
    sources: ["Britannica: Louis Pasteur"],
    counterexample: false,
  },
  {
    id: "marie-curie-skip",
    skip: true,
  },
  {
    id: "bohr",
    name: "尼尔斯·玻尔",
    nameEn: "Niels Bohr",
    gender: "male",
    era: "1885–1962",
    dynastyOrPeriod: "20 世纪",
    country: "丹麦",
    region: "哥本哈根",
    birthPlace: "哥本哈根",
    socialClass: "学者",
    field: ["科学", "物理"],
    birth: {
      year: 1885,
      month: 10,
      day: 7,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["量子论", "哥本哈根学派", "国际学术网络"],
    },
    bio: "量子物理学奠基人之一。",
    situation: "建立哥本哈根学派，影响 20 世纪物理与原子能政治。",
    fitAssessment: "部分符合",
    analysisNotes: "学人贵格附会常见。小型科学强国的制度投资更关键。",
    classicalRefs: ["子平：名位须看时势"],
    sources: ["Nobel Prize biography: Niels Bohr"],
    counterexample: false,
  },
  {
    id: "hawking",
    name: "斯蒂芬·霍金",
    nameEn: "Stephen Hawking",
    gender: "male",
    era: "1942–2018",
    dynastyOrPeriod: "当代",
    country: "英国",
    region: "英格兰",
    birthPlace: "牛津",
    socialClass: "学者",
    field: ["科学", "物理"],
    birth: {
      year: 1942,
      month: 1,
      day: 8,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["黑洞理论", "科普传播", "残疾与科研"],
    },
    bio: "理论物理学家与科普作家。",
    situation: "在渐冻症条件下持续科研与大众科学传播。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：严重疾病与卓越智力成就并存，打破‘疾厄则无成’的粗糙命理话术。",
    classicalRefs: ["三命通会：疾厄与才艺须分论"],
    sources: ["Britannica: Stephen Hawking"],
    counterexample: true,
  },
  {
    id: "grace-hopper",
    name: "格蕾丝·霍珀",
    nameEn: "Grace Hopper",
    gender: "female",
    era: "1906–1992",
    dynastyOrPeriod: "20 世纪美国",
    country: "美国",
    region: "纽约",
    birthPlace: "纽约",
    socialClass: "军人/计算机科学家",
    field: ["计算机", "科学", "军事"],
    birth: {
      year: 1906,
      month: 12,
      day: 9,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["编译器先驱", "海军服役", "女性 STEM"],
    },
    bio: "计算机编译技术先驱，美国海军少将。",
    situation: "推动高级编程语言与军用计算，打破性别职业壁垒。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤、官星并行叙事易贴合。战时计算需求与军队人事更关键。",
    classicalRefs: ["子平：才官须看时势"],
    sources: ["Britannica: Grace Hopper"],
    counterexample: false,
  },
  {
    id: "katherine-johnson",
    name: "凯瑟琳·约翰逊",
    nameEn: "Katherine Johnson",
    gender: "female",
    era: "1918–2020",
    dynastyOrPeriod: "20 世纪美国",
    country: "美国",
    region: "西弗吉尼亚",
    birthPlace: "怀特萨尔弗斯普林斯",
    socialClass: "数学家",
    field: ["科学", "数学", "工程"],
    birth: {
      year: 1918,
      month: 8,
      day: 26,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["航天轨道计算", "种族与性别壁垒", "后世表彰滞后"],
    },
    bio: "NASA 关键轨道计算关键数学家。",
    situation: "在隔离制度下完成关键计算，公共承认显著滞后。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：关键工程贡献长期被忽视。种族与性别结构不能被‘格局低’解释。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["NASA biography / Britannica: Katherine Johnson"],
    counterexample: true,
  },
  {
    id: "tolstoy",
    name: "列夫·托尔斯泰",
    nameEn: "Leo Tolstoy",
    gender: "male",
    era: "1828–1910",
    dynastyOrPeriod: "俄罗斯帝国",
    country: "俄罗斯",
    region: "图拉",
    birthPlace: "亚斯纳亚波利亚纳",
    socialClass: "贵族文人",
    field: ["文学", "思想", "宗教"],
    birth: {
      year: 1828,
      month: 9,
      day: 9,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "公历换算后的常用生日；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["长篇巨著", "道德宗教转向", "贵族批判"],
    },
    bio: "俄罗斯文学巨匠，《战争与和平》作者。",
    situation: "由贵族军官转为道德宗教思想家，影响全球文学。",
    fitAssessment: "部分符合",
    analysisNotes: "印食、伤官叙事易贴合。农奴制改革与印刷文化更关键。",
    classicalRefs: ["滴天髓：才学须看际遇"],
    sources: ["Britannica: Leo Tolstoy"],
    counterexample: false,
  },
  {
    id: "cervantes",
    name: "米格尔·德·塞万提斯",
    nameEn: "Miguel de Cervantes",
    gender: "male",
    era: "1547–1616",
    dynastyOrPeriod: "西班牙黄金时代",
    country: "西班牙",
    region: "阿尔卡拉",
    birthPlace: "阿尔卡拉-德埃纳雷斯",
    socialClass: "军人/税吏/文人",
    field: ["文学"],
    birth: {
      year: 1547,
      month: 9,
      day: 29,
      hour: null,
      calendar: "gregorian",
      precision: "uncertain",
      note: "受洗日期 1547-10-09 有记载，生日常取 9 月 29 日，精确性存讨论；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "mixed",
      confidence: "low",
      patternTags: ["现代小说先声", "军旅与囚禁", "晚成"],
    },
    bio: "《堂吉诃德》作者，西班牙语文学巨匠。",
    situation: "军旅、被俘与小吏生涯后写出影响世界的小说。",
    fitAssessment: "部分符合",
    analysisNotes: "晚成、驿马附会常见。帝国扩张与印刷市场更关键。",
    classicalRefs: ["三命通会：驿马类神须谨慎比附"],
    sources: ["Britannica: Miguel de Cervantes"],
    counterexample: false,
  },
  {
    id: "picasso",
    name: "巴勃罗·毕加索",
    nameEn: "Pablo Picasso",
    gender: "male",
    era: "1881–1973",
    dynastyOrPeriod: "20 世纪",
    country: "西班牙",
    region: "马拉加",
    birthPlace: "马拉加",
    socialClass: "职业画家",
    field: ["艺术"],
    birth: {
      year: 1881,
      month: 10,
      day: 25,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰有传说但不采信。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["立体主义", "多风格嬗变", "艺术市场"],
    },
    bio: "20 世纪视觉艺术关键革新者之一。",
    situation: "在巴黎艺术市场与现代主义运动中确立全球影响。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤、偏财艺术市场叙事易套用。画廊制度与收藏资本更关键。",
    classicalRefs: ["子平：才财相生标签勿神话化"],
    sources: ["Britannica: Pablo Picasso"],
    counterexample: false,
  },
  {
    id: "marquez",
    name: "加夫列尔·加西亚·马尔克斯",
    nameEn: "Gabriel García Márquez",
    gender: "male",
    era: "1927–2014",
    dynastyOrPeriod: "20 世纪拉美",
    country: "哥伦比亚",
    region: "马格达莱纳",
    birthPlace: "阿拉卡塔卡",
    socialClass: "报人/小说家",
    field: ["文学", "新闻"],
    birth: {
      year: 1927,
      month: 3,
      day: 6,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["魔幻现实主义", "拉美文学爆炸", "诺贝尔文学奖"],
    },
    bio: "《百年孤独》作者，诺贝尔文学奖得主。",
    situation: "记者生涯与拉美政治经验滋养其小说世界。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤生秀易贴合。翻译网络与‘文学爆炸’出版机制更关键。",
    classicalRefs: ["滴天髓：文才须看际遇"],
    sources: ["Nobel Prize biography: Gabriel García Márquez"],
    counterexample: false,
  },
  {
    id: "pele",
    name: "贝利",
    nameEn: "Pelé",
    gender: "male",
    era: "1940–2022",
    dynastyOrPeriod: "当代",
    country: "巴西",
    region: "米纳斯吉拉斯",
    birthPlace: "特雷斯科拉索伊斯",
    socialClass: "职业运动员",
    field: ["体育"],
    birth: {
      year: 1940,
      month: 10,
      day: 23,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["足球巨星", "世界杯", "全球传媒明星"],
    },
    bio: "足球史上标志性运动员之一。",
    situation: "以俱乐部与国家队成就成为全球体育偶像。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤、偏财名利叙事易套用。职业联赛与电视转播工业更关键。",
    classicalRefs: ["子平：名利标签须看时势"],
    sources: ["Britannica: Pelé"],
    counterexample: false,
  },
  {
    id: "muhammad-ali",
    name: "穆罕默德·阿里",
    nameEn: "Muhammad Ali",
    gender: "male",
    era: "1942–2016",
    dynastyOrPeriod: "当代",
    country: "美国",
    region: "肯塔基",
    birthPlace: "路易斯维尔",
    socialClass: "职业运动员/社会活动家",
    field: ["体育", "社会运动", "宗教"],
    birth: {
      year: 1942,
      month: 1,
      day: 17,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["拳王", "反战拒役", "种族政治"],
    },
    bio: "拳击巨星与民权/反战公共人物。",
    situation: "竞技成就与政治立场交织，重塑运动员公共角色。",
    fitAssessment: "部分符合",
    analysisNotes: "七杀、伤官对抗叙事易贴合。越战、民权与电视时代更关键。",
    classicalRefs: ["子平：官杀战勿直接史实化"],
    sources: ["Britannica: Muhammad Ali"],
    counterexample: false,
  },
  {
    id: "jesse-owens",
    name: "杰西·欧文斯",
    nameEn: "Jesse Owens",
    gender: "male",
    era: "1913–1980",
    dynastyOrPeriod: "20 世纪",
    country: "美国",
    region: "亚拉巴马",
    birthPlace: "橡树村",
    socialClass: "运动员",
    field: ["体育", "社会"],
    birth: {
      year: 1913,
      month: 9,
      day: 12,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["柏林奥运", "反种族主义象征", "赛后困顿"],
    },
    bio: "1936 年柏林奥运会田径明星。",
    situation: "以成绩冲击纳粹种族宣传，回国后仍面临种族歧视与经济困境。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：奥运荣耀与回国待遇严重脱节。不能用‘获奖格局’解释社会结构。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["Britannica: Jesse Owens"],
    counterexample: true,
  },
  {
    id: "nadia-comaneci",
    name: "纳迪娅·科马内奇",
    nameEn: "Nadia Comăneci",
    gender: "female",
    era: "1961–",
    dynastyOrPeriod: "当代",
    country: "罗马尼亚",
    region: "巴克乌",
    birthPlace: "独脚村（Onești）",
    socialClass: "职业运动员",
    field: ["体育"],
    birth: {
      year: 1961,
      month: 11,
      day: 12,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["奥运满分", "国家体育体制", "冷战体育"],
    },
    bio: "体操史上首位奥运满分传奇运动员。",
    situation: "在国家集训体制下创造历史成绩，后移居北美。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤、童星叙事易套用。社会主义体育举国体制更关键。",
    classicalRefs: ["子平：才艺与名位须看时势"],
    sources: ["Britannica: Nadia Comăneci"],
    counterexample: false,
  },
  {
    id: "maradona",
    name: "迭戈·马拉多纳",
    nameEn: "Diego Maradona",
    gender: "male",
    era: "1960–2020",
    dynastyOrPeriod: "当代",
    country: "阿根廷",
    region: "布宜诺斯艾利斯",
    birthPlace: "拉努斯",
    socialClass: "职业运动员",
    field: ["体育"],
    birth: {
      year: 1960,
      month: 10,
      day: 30,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["足球巨星", "争议与神化", "底层跃升"],
    },
    bio: "阿根廷足球传奇，1986 年世界杯关键人物。",
    situation: "竞技巅峰与个人争议并存，成为拉美大众文化符号。",
    fitAssessment: "部分符合",
    analysisNotes: "偏财、伤官、七杀混搭附会极多。职业足球全球化与媒体神化更关键。",
    classicalRefs: ["三命通会：名气与祸福须分看"],
    sources: ["Britannica: Diego Maradona"],
    counterexample: false,
  },
  {
    id: "martin-luther-king",
    name: "马丁·路德·金",
    nameEn: "Martin Luther King Jr.",
    gender: "male",
    era: "1929–1968",
    dynastyOrPeriod: "20 世纪美国",
    country: "美国",
    region: "佐治亚",
    birthPlace: "亚特兰大",
    socialClass: "牧师/民权领袖",
    field: ["社会运动", "宗教", "政治"],
    birth: {
      year: 1929,
      month: 1,
      day: 15,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["非暴力抗争", "民权立法", "遇刺"],
    },
    bio: "美国民权运动核心领袖，诺贝尔和平奖得主。",
    situation: "以教会网络组织非暴力运动，推动民权立法，后遇刺。",
    fitAssessment: "部分符合",
    analysisNotes: "印星、正官、七杀叙事易神话化。黑人教会与法律策略联盟更关键。",
    classicalRefs: ["滴天髓：事功须看时势"],
    sources: ["Nobel Prize biography / Britannica: Martin Luther King, Jr."],
    counterexample: false,
  },
  {
    id: "che-guevara",
    name: "切·格瓦拉",
    nameEn: "Che Guevara",
    gender: "male",
    era: "1928–1967",
    dynastyOrPeriod: "20 世纪",
    country: "阿根廷",
    region: "罗萨里奥",
    birthPlace: "罗萨里奥",
    socialClass: "革命者/医生出身",
    field: ["政治", "军事", "社会运动"],
    birth: {
      year: 1928,
      month: 6,
      day: 14,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["古巴革命", "国际游击", "符号化"],
    },
    bio: "古巴革命重要人物，后成为全球左翼符号。",
    situation: "参与古巴革命后继续输出武装斗争，在玻利维亚被杀。",
    fitAssessment: "部分符合",
    analysisNotes: "七杀、驿马革命叙事极易附会。冷战代理冲突与宣传工业更关键。",
    classicalRefs: ["子平：官杀战勿直接史实化"],
    sources: ["Britannica: Che Guevara"],
    counterexample: false,
  },
  {
    id: "simon-bolivar",
    name: "西蒙·玻利瓦尔",
    nameEn: "Simón Bolívar",
    gender: "male",
    era: "1783–1830",
    dynastyOrPeriod: "拉丁美洲独立战争",
    country: "委内瑞拉",
    region: "加拉加斯",
    birthPlace: "加拉加斯",
    socialClass: "克里奥尔精英/军人政治家",
    field: ["政治", "军事"],
    birth: {
      year: 1783,
      month: 7,
      day: 24,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["独立战争", "解放者叙事", "共和国实验"],
    },
    bio: "南美多国独立运动关键领袖。",
    situation: "领导反殖民战争并尝试大哥伦比亚政治整合，最终受挫。",
    fitAssessment: "部分符合",
    analysisNotes: "帝王将相格局附会常见。大西洋革命浪潮与克里奥尔精英政治更关键。",
    classicalRefs: ["渊海子平：官星与权位须分看"],
    sources: ["Britannica: Simón Bolívar"],
    counterexample: false,
  },
  {
    id: "ho-chi-minh",
    name: "胡志明",
    nameEn: "Ho Chi Minh",
    gender: "male",
    era: "1890–1969",
    dynastyOrPeriod: "20 世纪",
    country: "越南",
    region: "义安",
    birthPlace: "黄稠村一带",
    socialClass: "革命者/政治家",
    field: ["政治", "军事"],
    birth: {
      year: 1890,
      month: 5,
      day: 19,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["民族独立", "共产主义运动", "长期战争"],
    },
    bio: "越南独立运动与国家建构关键领导人。",
    situation: "在殖民、世界大战与冷战交错中领导独立战争。",
    fitAssessment: "部分符合",
    analysisNotes: "七杀、驿马、印星叙事易神话化。殖民解体与冷战结构更关键。",
    classicalRefs: ["子平：官杀战勿直接史实化"],
    sources: ["Britannica: Ho Chi Minh"],
    counterexample: false,
  },
  {
    id: "jose-rizal",
    name: "何塞·黎刹",
    nameEn: "José Rizal",
    gender: "male",
    era: "1861–1896",
    dynastyOrPeriod: "19 世纪东南亚",
    country: "菲律宾",
    region: "拉古纳",
    birthPlace: "卡兰巴",
    socialClass: "知识分子/医生",
    field: ["文学", "政治", "社会运动"],
    birth: {
      year: 1861,
      month: 6,
      day: 19,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["民族小说", "改革派", "就义"],
    },
    bio: "菲律宾民族英雄，小说家与眼科医生。",
    situation: "以文学与政论推动改革，遭殖民当局处决。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官见官、忠烈附会常见。印刷公共领域与殖民法律更关键。",
    classicalRefs: ["子平：伤官见官勿史实化"],
    sources: ["Britannica: José Rizal"],
    counterexample: false,
  },
  {
    id: "sukarno",
    name: "苏加诺",
    nameEn: "Sukarno",
    gender: "male",
    era: "1901–1970",
    dynastyOrPeriod: "20 世纪",
    country: "印度尼西亚",
    region: "东爪哇",
    birthPlace: "泗水",
    socialClass: "政治家",
    field: ["政治"],
    birth: {
      year: 1901,
      month: 6,
      day: 6,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["独立建国", "不结盟", "权力更迭"],
    },
    bio: "印度尼西亚建国总统。",
    situation: "领导独立并主导早期国家建构，后在政变浪潮中失势。",
    fitAssessment: "部分符合",
    analysisNotes: "帝王格局附会常见。去殖民化与冷战军方政治更关键。",
    classicalRefs: ["渊海子平：官星与权位须分看"],
    sources: ["Britannica: Sukarno"],
    counterexample: false,
  },
  {
    id: "lee-kuan-yew",
    name: "李光耀",
    nameEn: "Lee Kuan Yew",
    gender: "male",
    era: "1923–2015",
    dynastyOrPeriod: "当代",
    country: "新加坡",
    region: "新加坡",
    birthPlace: "新加坡",
    socialClass: "政治家/律师",
    field: ["政治", "法律"],
    birth: {
      year: 1923,
      month: 9,
      day: 16,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["城市国家治理", "威权发展主义", "精英行政"],
    },
    bio: "新加坡建国总理。",
    situation: "以强国家与精英官僚推动城市国家现代化，争议与成就并存。",
    fitAssessment: "部分符合",
    analysisNotes: "正官得位叙事易事后附会。港口地缘与冷战投资转移更关键。",
    classicalRefs: ["渊海子平：官星清浊与权位须分看"],
    sources: ["Britannica: Lee Kuan Yew"],
    counterexample: false,
  },
  {
    id: "haile-selassie",
    name: "海尔·塞拉西一世",
    nameEn: "Haile Selassie",
    gender: "male",
    era: "1892–1975",
    dynastyOrPeriod: "20 世纪非洲",
    country: "埃塞俄比亚",
    region: "哈勒尔",
    birthPlace: "埃杰萨戈罗一带",
    socialClass: "帝王",
    field: ["政治", "外交"],
    birth: {
      year: 1892,
      month: 7,
      day: 23,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["抗意战争", "非盟前史", "帝制终结"],
    },
    bio: "埃塞俄比亚皇帝，非洲外交象征人物。",
    situation: "抵抗意大利侵略并参与战后国际组织，后在政变中被废黜。",
    fitAssessment: "部分符合",
    analysisNotes: "真龙天子叙事在拉塔法里信仰中被神化。殖民与冷战政治才是主因。",
    classicalRefs: ["滴天髓：君相造命说须历史化"],
    sources: ["Britannica: Haile Selassie I"],
    counterexample: false,
  },
  {
    id: "nkrumah",
    name: "克瓦米·恩克鲁玛",
    nameEn: "Kwame Nkrumah",
    gender: "male",
    era: "1909–1972",
    dynastyOrPeriod: "20 世纪非洲",
    country: "加纳",
    region: "西部省",
    birthPlace: "恩克罗富尔",
    socialClass: "政治家",
    field: ["政治", "思想"],
    birth: {
      year: 1909,
      month: 9,
      day: 21,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["去殖民化", "泛非主义", "政变下台"],
    },
    bio: "加纳首任总理与总统，泛非主义代表人物。",
    situation: "领导黄金海岸独立，后在政变中流亡。",
    fitAssessment: "部分符合",
    analysisNotes: "驿马、官杀叙事易套用。去殖民浪潮与冷战干预更关键。",
    classicalRefs: ["子平：官杀战勿直接史实化"],
    sources: ["Britannica: Kwame Nkrumah"],
    counterexample: false,
  },
  {
    id: "desmond-tutu",
    name: "德斯蒙德·图图",
    nameEn: "Desmond Tutu",
    gender: "male",
    era: "1931–2021",
    dynastyOrPeriod: "当代非洲",
    country: "南非",
    region: "北开普",
    birthPlace: "克莱克斯多普",
    socialClass: "教士/人权活动家",
    field: ["宗教", "社会运动", "政治"],
    birth: {
      year: 1931,
      month: 10,
      day: 7,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["反种族隔离", "真相与和解", "圣公会网络"],
    },
    bio: "南非圣公会大主教，反种族隔离与和解进程关键人物。",
    situation: "以教会道德权威推动抗争与转型正义。",
    fitAssessment: "部分符合",
    analysisNotes: "印星、正官道德领袖叙事易贴合。教会跨国网络与谈判政治更关键。",
    classicalRefs: ["滴天髓：事功须看时势"],
    sources: ["Nobel Prize biography: Desmond Tutu"],
    counterexample: false,
  },
  {
    id: "chopin",
    name: "弗雷德里克·肖邦",
    nameEn: "Frédéric Chopin",
    gender: "male",
    era: "1810–1849",
    dynastyOrPeriod: "19 世纪欧洲",
    country: "波兰/法国",
    region: "马佐夫舍/巴黎",
    birthPlace: "热拉佐瓦沃拉",
    socialClass: "作曲家/钢琴家",
    field: ["艺术", "音乐"],
    birth: {
      year: 1810,
      month: 3,
      day: 1,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行（亦有 2 月 22 日说，本库取常用 3 月 1 日并标需谨慎）；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "mixed",
      confidence: "medium",
      patternTags: ["浪漫主义钢琴", "流亡巴黎", "民族情感"],
    },
    bio: "浪漫主义钢琴音乐代表作曲家。",
    situation: "在巴黎沙龙与出版市场中确立地位，英年早逝。",
    fitAssessment: "部分符合",
    analysisNotes: "才名短寿叙事易命理化。流亡音乐家市场与肺结核医学史更关键。",
    classicalRefs: ["三命通会：疾厄与才艺须分论"],
    sources: ["Britannica: Frédéric Chopin"],
    counterexample: false,
  },
  {
    id: "goethe",
    name: "约翰·沃尔夫冈·冯·歌德",
    nameEn: "Johann Wolfgang von Goethe",
    gender: "male",
    era: "1749–1832",
    dynastyOrPeriod: "启蒙与浪漫主义之际",
    country: "德意志",
    region: "法兰克福",
    birthPlace: "法兰克福",
    socialClass: "士绅/宫廷官员/文人",
    field: ["文学", "思想", "科学"],
    birth: {
      year: 1749,
      month: 8,
      day: 28,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰有记载传说，本库不采信为可靠字段。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["魏玛古典", "跨领域写作", "宫廷任职"],
    },
    bio: "德语文学巨匠，《浮士德》作者。",
    situation: "在魏玛宫廷与欧洲文学公共领域中长期写作。",
    fitAssessment: "部分符合",
    analysisNotes: "文昌贵格附会常见。宫廷Patronage 与印刷文化更关键。",
    classicalRefs: ["滴天髓：才学须看际遇"],
    sources: ["Britannica: Johann Wolfgang von Goethe"],
    counterexample: false,
  },
  {
    id: "kant",
    name: "伊曼努尔·康德",
    nameEn: "Immanuel Kant",
    gender: "male",
    era: "1724–1804",
    dynastyOrPeriod: "启蒙时代",
    country: "德意志",
    region: "东普鲁士",
    birthPlace: "柯尼斯堡",
    socialClass: "学者",
    field: ["思想", "哲学"],
    birth: {
      year: 1724,
      month: 4,
      day: 22,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["批判哲学", "大学体制", "规律生活传说"],
    },
    bio: "德国古典哲学关键奠基人。",
    situation: "长期在柯尼斯堡大学任教，塑造现代认识论与道德哲学。",
    fitAssessment: "部分符合",
    analysisNotes: "印星学人叙事易贴合。大学教职结构与启蒙出版网络更关键。",
    classicalRefs: ["子平：才学标签勿神话化"],
    sources: ["Britannica: Immanuel Kant"],
    counterexample: false,
  },
  {
    id: "marx",
    name: "卡尔·马克思",
    nameEn: "Karl Marx",
    gender: "male",
    era: "1818–1883",
    dynastyOrPeriod: "19 世纪欧洲",
    country: "德意志",
    region: "莱茵兰",
    birthPlace: "特里尔",
    socialClass: "知识分子/流亡政论家",
    field: ["思想", "政治", "经济"],
    birth: {
      year: 1818,
      month: 5,
      day: 5,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["批判资本主义", "流亡写作", "后世政治化"],
    },
    bio: "马克思主义创始人之一，《资本论》作者。",
    situation: "长期流亡伦敦从事研究与政论，身后思想被全球政治运动征用。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：生前穷困与身后巨大政治影响并存。思想史与工人运动组织不能化约为日柱。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["Britannica: Karl Marx"],
    counterexample: true,
  },
  {
    id: "freud",
    name: "西格蒙德·弗洛伊德",
    nameEn: "Sigmund Freud",
    gender: "male",
    era: "1856–1939",
    dynastyOrPeriod: "近现代欧洲",
    country: "奥地利",
    region: "摩拉维亚/维也纳",
    birthPlace: "弗莱贝格（今普日博尔）",
    socialClass: "医师/学者",
    field: ["医学", "思想", "学术"],
    birth: {
      year: 1856,
      month: 5,
      day: 6,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["精神分析", "争议学说", "维也纳知识圈"],
    },
    bio: "精神分析学派创立者。",
    situation: "在维也纳建立学派，学说深刻影响人文学与大众文化，亦饱受科学争议。",
    fitAssessment: "部分符合",
    analysisNotes: "印食、伤官叙事易贴合。医学职业化与犹太知识分子城市网络更关键。",
    classicalRefs: ["三命通会：才学与争议须分看"],
    sources: ["Britannica: Sigmund Freud"],
    counterexample: false,
  },
  {
    id: "jung",
    name: "卡尔·荣格",
    nameEn: "Carl Jung",
    gender: "male",
    era: "1875–1961",
    dynastyOrPeriod: "近现代欧洲",
    country: "瑞士",
    region: "图尔高",
    birthPlace: "凯斯维尔",
    socialClass: "医师/学者",
    field: ["医学", "思想", "学术"],
    birth: {
      year: 1875,
      month: 7,
      day: 26,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["分析心理学", "与弗洛伊德分裂", "集体无意识"],
    },
    bio: "分析心理学创立者。",
    situation: "自精神分析分裂后建立独立学派，影响宗教与文化研究。",
    fitAssessment: "部分符合",
    analysisNotes: "印星、伤官自立门户叙事易套用。学术建制与瑞士诊所实践更关键。",
    classicalRefs: ["子平：才学标签勿神话化"],
    sources: ["Britannica: Carl Jung"],
    counterexample: false,
  },
  {
    id: "harriet-tubman",
    name: "哈丽特·塔布曼",
    nameEn: "Harriet Tubman",
    gender: "female",
    era: "约 1822–1913",
    dynastyOrPeriod: "19 世纪美国",
    country: "美国",
    region: "马里兰",
    birthPlace: "多彻斯特县",
    socialClass: "奴隶出身废奴活动家",
    field: ["社会运动", "军事"],
    birth: {
      year: 1822,
      hour: null,
      calendar: "gregorian",
      precision: "year-only",
      note: "奴隶制下精确生日不确，约 1822 年；时辰未知。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["地下铁路", "废奴", "内战侦察"],
      shiShenTendency: ["七杀", "伤官", "正印"],
    },
    bio: "废奴运动英雄，多次引导奴隶逃亡。",
    situation: "在极端暴力结构下组织救援，并参与内战相关任务。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：精确生辰缺失却留下巨大历史能动性。社会结构与组织网络不能被日柱替代。",
    classicalRefs: ["子平：无确切生辰则不可硬排格局"],
    sources: ["National Park Service / Britannica: Harriet Tubman"],
    counterexample: true,
  },
  {
    id: "cleopatra",
    name: "克娄巴特拉七世",
    nameEn: "Cleopatra VII",
    gender: "female",
    era: "前 69–前 30",
    dynastyOrPeriod: "托勒密埃及",
    country: "古埃及",
    region: "亚历山大",
    birthPlace: "亚历山大（传统）",
    socialClass: "帝王",
    field: ["政治", "外交"],
    birth: {
      year: -69,
      hour: null,
      calendar: "traditional-approx",
      precision: "uncertain",
      note: "生年约公元前 69，精确月日时辰不可考；后世传奇不可当作排盘依据。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["女主执政", "罗马政治博弈", "传奇层累"],
      shiShenTendency: ["正官", "偏财", "伤官"],
    },
    bio: "托勒密王朝末代女统治者。",
    situation: "在罗马内战格局中维系埃及主权，最终王朝覆灭。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：被后世极度命理化与色情化的女主。罗马霸权政治才是主叙事。",
    classicalRefs: ["三命通会：神异叙事不可替代史料"],
    sources: ["Britannica: Cleopatra"],
    counterexample: true,
  },
  {
    id: "mansa-musa",
    name: "曼萨·穆萨",
    nameEn: "Mansa Musa",
    gender: "male",
    era: "约 1280–约 1337",
    dynastyOrPeriod: "马里帝国",
    country: "马里",
    region: "西非萨赫勒",
    birthPlace: "不详",
    socialClass: "帝王",
    field: ["政治", "商业", "宗教"],
    birth: {
      year: 1280,
      hour: null,
      calendar: "traditional-approx",
      precision: "uncertain",
      note: "生卒年多为估计，朝觐事迹有阿拉伯史料，精确生辰不可考。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["黄金贸易", "朝觐外交", "西非帝国"],
      shiShenTendency: ["偏财", "正官", "正印"],
    },
    bio: "马里帝国统治者，以朝觐途中展示财富闻名。",
    situation: "通过跨撒哈拉贸易与伊斯兰网络巩固帝国影响力。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：几乎无可靠生辰，却在全球经济史中地位明确。破除‘无八字则无历史重要性’偏见。",
    classicalRefs: ["子平：无确切生辰则不可硬排格局"],
    sources: ["Britannica: Mūsā I of Mali"],
    counterexample: true,
  },
  {
    id: "hypatia-skip",
    skip: true,
  },
  {
    id: "aviccena-skip",
    skip: true,
  },
  {
    id: "ibn-sina-alias-skip",
    skip: true,
  },
  {
    id: "maimonides",
    name: "迈蒙尼德",
    nameEn: "Maimonides",
    gender: "male",
    era: "1138–1204",
    dynastyOrPeriod: "中世纪地中海",
    country: "西班牙/埃及",
    region: "科尔多瓦—开罗",
    birthPlace: "科尔多瓦",
    socialClass: "学者/医师",
    field: ["宗教", "医学", "思想"],
    birth: {
      year: 1138,
      month: 3,
      day: 30,
      hour: null,
      calendar: "gregorian",
      precision: "uncertain",
      note: "传统纪念日期广泛流传；历史精确性仍有讨论。",
    },
    chartTags: {
      hourKnown: false,
      source: "mixed",
      confidence: "low",
      patternTags: ["犹太律法", "医学实践", "跨文明迁徙"],
    },
    bio: "中世纪犹太思想与医学巨匠。",
    situation: "因阿尔摩哈德迫害迁徙至埃及，兼任医师与社团领袖。",
    fitAssessment: "资料不足",
    analysisNotes: "生辰精确性有限；成就依赖地中海犹太—伊斯兰学术网络。",
    classicalRefs: ["子平：生辰不确则不可强断"],
    sources: ["Britannica: Moses Maimonides"],
    counterexample: false,
  },
  {
    id: "hildegard",
    name: "宾根的希尔德加德",
    nameEn: "Hildegard of Bingen",
    gender: "female",
    era: "1098–1179",
    dynastyOrPeriod: "中世纪欧洲",
    country: "德意志",
    region: "莱茵兰",
    birthPlace: "伯默斯海姆一带",
    socialClass: "修道院院长/学者",
    field: ["宗教", "医学", "艺术", "音乐"],
    birth: {
      year: 1098,
      hour: null,
      calendar: "traditional-approx",
      precision: "year-only",
      note: "生年约 1098，精确月日时辰不足。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["修道院知识", "医学与音乐", "女性神学家"],
      shiShenTendency: ["正印", "食神", "伤官"],
    },
    bio: "中世纪女修院院长，神学家、医学与音乐创作者。",
    situation: "在修道院制度中留下跨领域著作与书信。",
    fitAssessment: "资料不足",
    analysisNotes: "生辰不足；展示中世纪女性知识生产，禁止伪造时柱。",
    classicalRefs: ["渊海子平：时辰不明难定全局"],
    sources: ["Britannica: St. Hildegard"],
    counterexample: false,
  },
  {
    id: "florence-nightingale-skip",
    skip: true,
  },
  {
    id: "elizabeth-blackwell",
    name: "伊丽莎白·布莱克韦尔",
    nameEn: "Elizabeth Blackwell",
    gender: "female",
    era: "1821–1910",
    dynastyOrPeriod: "19 世纪",
    country: "英国/美国",
    region: "布里斯托尔出生/美国行医",
    birthPlace: "布里斯托尔",
    socialClass: "医师",
    field: ["医学", "教育", "社会运动"],
    birth: {
      year: 1821,
      month: 2,
      day: 3,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["首位女医学生", "医学教育", "性别壁垒"],
    },
    bio: "英语世界最早获得医学学位的女性医生之一。",
    situation: "突破医学院性别限制，推动女性医学教育。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官见官、印星叙事易贴合。专业门槛改革与废奴家庭网络更关键。",
    classicalRefs: ["子平：才官须看时势"],
    sources: ["Britannica: Elizabeth Blackwell"],
    counterexample: false,
  },
  {
    id: "amelia-earhart",
    name: "阿梅莉亚·埃尔哈特",
    nameEn: "Amelia Earhart",
    gender: "female",
    era: "1897–1937",
    dynastyOrPeriod: "20 世纪",
    country: "美国",
    region: "堪萨斯",
    birthPlace: "阿奇森",
    socialClass: "飞行员/公众人物",
    field: ["工程", "社会运动", "体育"],
    birth: {
      year: 1897,
      month: 7,
      day: 24,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["航空先驱", "女性飞行", "失踪成谜"],
    },
    bio: "早期航空传奇人物，首位独自飞越大西洋的女性飞行员之一。",
    situation: "以飞行纪录挑战性别规范，环球飞行中失踪。",
    fitAssessment: "部分符合",
    analysisNotes: "驿马、七杀冒险叙事易神话化。航空工业与媒体赞助更关键。",
    classicalRefs: ["三命通会：驿马类神须谨慎比附"],
    sources: ["Britannica: Amelia Earhart"],
    counterexample: false,
  },
  {
    id: "edmund-hillary",
    name: "埃德蒙·希拉里",
    nameEn: "Edmund Hillary",
    gender: "male",
    era: "1919–2008",
    dynastyOrPeriod: "当代",
    country: "新西兰",
    region: "奥克兰",
    birthPlace: "奥克兰",
    socialClass: "探险家",
    field: ["体育", "社会"],
    birth: {
      year: 1919,
      month: 7,
      day: 20,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["珠峰首登", "雪尔帕协作", "后期慈善"],
    },
    bio: "与丹增·诺尔盖完成珠穆朗玛峰首登的探险家。",
    situation: "登山成就后长期参与喜马拉雅地区援助。",
    fitAssessment: "部分符合",
    analysisNotes: "驿马、七杀附会常见。协作团队、氧气装备与媒体民族叙事更关键。",
    classicalRefs: ["三命通会：驿马类神须谨慎比附"],
    sources: ["Britannica: Edmund Hillary"],
    counterexample: false,
  },
  {
    id: "tenzing-norgay",
    name: "丹增·诺尔盖",
    nameEn: "Tenzing Norgay",
    gender: "male",
    era: "约 1914–1986",
    dynastyOrPeriod: "当代",
    country: "尼泊尔/印度",
    region: "喜马拉雅",
    birthPlace: "珠峰地区（记载有异）",
    socialClass: "雪尔帕登山家",
    field: ["体育"],
    birth: {
      year: 1914,
      hour: null,
      calendar: "traditional-approx",
      precision: "uncertain",
      note: "生年约 1914，精确月日多方异说；时辰未知。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["珠峰首登", "雪尔帕贡献", "承认政治"],
      shiShenTendency: ["食神", "七杀", "正印"],
    },
    bio: "珠峰首登关键雪尔帕登山家。",
    situation: "长期被西方叙事边缘化，后逐渐获得更公平历史承认。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：关键贡献与公共承认不对称。殖民与种族叙事偏差不能用八字解释。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["Britannica: Tenzing Norgay"],
    counterexample: true,
  },
  {
    id: "bruce-lee",
    name: "李小龙",
    nameEn: "Bruce Lee",
    gender: "male",
    era: "1940–1973",
    dynastyOrPeriod: "当代",
    country: "中国/美国",
    region: "香港/加州",
    birthPlace: "旧金山",
    socialClass: "武术家/演员",
    field: ["艺术", "体育", "哲学"],
    birth: {
      year: 1940,
      month: 11,
      day: 27,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰有流传说法，本库不采信为可靠字段。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["功夫电影", "跨文化偶像", "早逝"],
    },
    bio: "武术家与功夫电影国际偶像。",
    situation: "以截拳道理念与电影打破好莱坞亚裔刻板印象，英年早逝。",
    fitAssessment: "部分符合",
    analysisNotes: "七杀、食伤、短寿才名附会极多。冷战港片工业与美国种族政治更关键。",
    classicalRefs: ["三命通会：寿夭与事功须分看"],
    sources: ["Britannica: Bruce Lee"],
    counterexample: false,
  },
  {
    id: "kurosawa",
    name: "黑泽明",
    nameEn: "Akira Kurosawa",
    gender: "male",
    era: "1910–1998",
    dynastyOrPeriod: "当代",
    country: "日本",
    region: "东京",
    birthPlace: "东京",
    socialClass: "电影导演",
    field: ["艺术"],
    birth: {
      year: 1910,
      month: 3,
      day: 23,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["世界电影", "时代剧", "国际影响"],
    },
    bio: "日本电影巨匠，影响全球导演世代。",
    situation: "在战后日本电影工业中确立国际声誉。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤生秀易套用。制片厂制度与国际电影节机制更关键。",
    classicalRefs: ["子平：才艺成就须看时势"],
    sources: ["Britannica: Kurosawa Akira"],
    counterexample: false,
  },
  {
    id: "miyazaki",
    name: "宫崎骏",
    nameEn: "Hayao Miyazaki",
    gender: "male",
    era: "1941–",
    dynastyOrPeriod: "当代",
    country: "日本",
    region: "东京",
    birthPlace: "东京",
    socialClass: "动画导演",
    field: ["艺术"],
    birth: {
      year: 1941,
      month: 1,
      day: 5,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["动画工业", "反战生态主题", "吉卜力"],
    },
    bio: "动画电影导演，吉卜力工作室核心创作者。",
    situation: "以长篇动画影响全球流行文化与环保审美。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤、印星叙事易贴合。动画工作室制度与家庭影院市场更关键。",
    classicalRefs: ["子平：才艺成就须看时势"],
    sources: ["公开人物年表 / 动画史综述"],
    counterexample: false,
  },
  {
    id: "anandibai-joshi",
    name: "阿南迪拜·乔希",
    nameEn: "Anandibai Joshi",
    gender: "female",
    era: "1865–1887",
    dynastyOrPeriod: "19 世纪印度",
    country: "印度",
    region: "马哈拉施特拉",
    birthPlace: "卡利亚恩一带",
    socialClass: "医师",
    field: ["医学", "教育", "社会运动"],
    birth: {
      year: 1865,
      month: 3,
      day: 31,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["早期女医生", "跨国留学", "早逝"],
    },
    bio: "最早获得西医学位的印度女性医生之一。",
    situation: "赴美学医后归国，英年早逝，成为教育史象征。",
    fitAssessment: "部分符合",
    analysisNotes: "才名短寿叙事易命理化。殖民医学教育与种姓性别结构更关键。",
    classicalRefs: ["三命通会：寿夭与事功须分看"],
    sources: ["公开传记与南亚妇女史综述"],
    counterexample: false,
  },
  {
    id: "sarojini-naidu",
    name: "萨罗吉尼·奈都",
    nameEn: "Sarojini Naidu",
    gender: "female",
    era: "1879–1949",
    dynastyOrPeriod: "近现代印度",
    country: "印度",
    region: "鸿德拉巴/西孟加拉关联",
    birthPlace: "海德拉巴",
    socialClass: "诗人/政治家",
    field: ["政治", "文学", "社会运动"],
    birth: {
      year: 1879,
      month: 2,
      day: 13,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["独立运动", "女诗人", "省督任职"],
    },
    bio: "印度独立运动领袖与诗人。",
    situation: "参与国大党政治并担任省级行政职务。",
    fitAssessment: "部分符合",
    analysisNotes: "才官双美叙事易贴合。殖民晚期精英民族主义网络更关键。",
    classicalRefs: ["渊海子平：才官须看时势"],
    sources: ["Britannica: Sarojini Naidu"],
    counterexample: false,
  },
  {
    id: "aung-san-suu-kyi",
    name: "昂山素季",
    nameEn: "Aung San Suu Kyi",
    gender: "female",
    era: "1945–",
    dynastyOrPeriod: "当代",
    country: "缅甸",
    region: "仰光",
    birthPlace: "仰光",
    socialClass: "政治家",
    field: ["政治", "社会运动"],
    birth: {
      year: 1945,
      month: 6,
      day: 19,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["民主运动", "软禁", "执政后争议"],
    },
    bio: "缅甸民主运动标志人物，后任国务资政，声誉因罗兴亚危机严重受损。",
    situation: "从异议领袖到执政者，国际评价剧烈翻转。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：同一人物先后被圣化与批判。命理无法解释复杂人权与军方政治。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["Britannica: Aung San Suu Kyi"],
    counterexample: true,
  },
  {
    id: "chulalongkorn",
    name: "朱拉隆功",
    nameEn: "Chulalongkorn",
    gender: "male",
    era: "1853–1910",
    dynastyOrPeriod: "近代暹罗",
    country: "泰国",
    region: "曼谷",
    birthPlace: "曼谷",
    socialClass: "帝王",
    field: ["政治", "改革"],
    birth: {
      year: 1853,
      month: 9,
      day: 20,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["现代化改革", "废除奴隶制", "维系独立"],
    },
    bio: "暹罗拉玛五世，推动近代改革。",
    situation: "在殖民压力下改革行政与社会，维系国家独立。",
    fitAssessment: "部分符合",
    analysisNotes: "明君格局附会常见。地缘缓冲与宫廷改革派联盟更关键。",
    classicalRefs: ["滴天髓：君相造命说须历史化"],
    sources: ["Britannica: Chulalongkorn"],
    counterexample: false,
  },
  {
    id: "gutenberg",
    name: "约翰内斯·古腾堡",
    nameEn: "Johannes Gutenberg",
    gender: "male",
    era: "约 1400–1468",
    dynastyOrPeriod: "中世纪晚期欧洲",
    country: "德意志",
    region: "美因茨",
    birthPlace: "美因茨",
    socialClass: "工匠/发明家",
    field: ["工程", "商业"],
    birth: {
      year: 1400,
      hour: null,
      calendar: "traditional-approx",
      precision: "uncertain",
      note: "生年约 1390s–1400，精确日期不可考。",
    },
    chartTags: {
      dayMaster: "不明",
      strength: "不明",
      hourKnown: false,
      source: "curated",
      confidence: "low",
      patternTags: ["活字印刷", "传媒革命", "生辰不可考"],
      shiShenTendency: ["食神", "偏财", "伤官"],
    },
    bio: "欧洲活字印刷术关键推动者。",
    situation: "印刷技术改变知识传播，但其个人生辰细节稀薄。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：改变世界的技术人物几乎无可靠生辰。技术史不等于命理可验证史。",
    classicalRefs: ["子平：无确切生辰则不可硬排格局"],
    sources: ["Britannica: Johannes Gutenberg"],
    counterexample: true,
  },
  {
    id: "copernicus",
    name: "尼古拉·哥白尼",
    nameEn: "Nicolaus Copernicus",
    gender: "male",
    era: "1473–1543",
    dynastyOrPeriod: "文艺复兴",
    country: "波兰",
    region: "托伦",
    birthPlace: "托伦",
    socialClass: "教士/学者",
    field: ["科学", "天文"],
    birth: {
      year: 1473,
      month: 2,
      day: 19,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["日心说", "科学革命前夜", "教会任职"],
    },
    bio: "提出日心说模型的天文学家。",
    situation: "在教会与大学网络中完成革命性天文学著作。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官破旧叙事易套用。数学天文学传统与印刷传播更关键。",
    classicalRefs: ["子平：伤官见官勿史实化"],
    sources: ["Britannica: Nicolaus Copernicus"],
    counterexample: false,
  },
  {
    id: "faraday",
    name: "迈克尔·法拉第",
    nameEn: "Michael Faraday",
    gender: "male",
    era: "1791–1867",
    dynastyOrPeriod: "19 世纪英国",
    country: "英国",
    region: "英格兰",
    birthPlace: "纽因顿",
    socialClass: "工匠出身学者",
    field: ["科学", "物理", "化学"],
    birth: {
      year: 1791,
      month: 9,
      day: 22,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["电磁学", "学徒出身", "皇家研究所"],
    },
    bio: "电磁学实验奠基者之一。",
    situation: "从装订学徒成长为顶尖实验科学家。",
    fitAssessment: "部分符合",
    analysisNotes:
      "寒门贵格叙事易命理化。学徒制、皇家研究所与工业革命需求更关键。",
    classicalRefs: ["滴天髓：才学须看际遇"],
    sources: ["Britannica: Michael Faraday"],
    counterexample: false,
  },
  {
    id: "mendel",
    name: "格雷戈尔·孟德尔",
    nameEn: "Gregor Mendel",
    gender: "male",
    era: "1822–1884",
    dynastyOrPeriod: "19 世纪",
    country: "奥匈帝国",
    region: "摩拉维亚",
    birthPlace: "海因岑多夫",
    socialClass: "修士/学者",
    field: ["科学", "生物学"],
    birth: {
      year: 1822,
      month: 7,
      day: 20,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期文献充分；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["遗传学奠基", "生前冷遇", "身后追认"],
    },
    bio: "经典遗传学奠基人。",
    situation: "修道院实验成果长期被忽视，20 世纪初才被重新发现。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：科学贡献与同时代承认严重错位。学科建制时机不能用八字解释。",
    classicalRefs: ["滴天髓：名实不符须看时势"],
    sources: ["Britannica: Gregor Mendel"],
    counterexample: true,
  },
  {
    id: "oppenheimer",
    name: "J·罗伯特·奥本海默",
    nameEn: "J. Robert Oppenheimer",
    gender: "male",
    era: "1904–1967",
    dynastyOrPeriod: "20 世纪",
    country: "美国",
    region: "纽约",
    birthPlace: "纽约",
    socialClass: "学者",
    field: ["科学", "物理", "军事"],
    birth: {
      year: 1904,
      month: 4,
      day: 22,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["曼哈顿工程", "核伦理", "政治审查"],
    },
    bio: "曼哈顿计划科学领导人之一。",
    situation: "主导原子弹研制后在安全听证中受挫，成为核时代象征。",
    fitAssessment: "部分符合",
    analysisNotes: "七杀、伤官、官非叙事易附会。大国战争动员与麦卡锡主义更关键。",
    classicalRefs: ["子平：官杀战勿直接史实化"],
    sources: ["Britannica: J. Robert Oppenheimer"],
    counterexample: false,
  },
  {
    id: "feynman",
    name: "理查德·费曼",
    nameEn: "Richard Feynman",
    gender: "male",
    era: "1918–1988",
    dynastyOrPeriod: "20 世纪",
    country: "美国",
    region: "纽约",
    birthPlace: "皇后区",
    socialClass: "学者",
    field: ["科学", "物理", "教育"],
    birth: {
      year: 1918,
      month: 5,
      day: 11,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期公开；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["量子电动力学", "教学风格", "挑战者号调查"],
    },
    bio: "理论物理学家，诺贝尔奖得主与科普文化偶像。",
    situation: "参与曼哈顿计划，后以教学与公开调查闻名。",
    fitAssessment: "部分符合",
    analysisNotes: "伤官、食神‘聪明外露’叙事易套用。加州理工与冷战物理资助更关键。",
    classicalRefs: ["子平：才学标签勿神话化"],
    sources: ["Nobel Prize biography: Richard P. Feynman"],
    counterexample: false,
  },
  {
    id: "li-sigang",
    name: "李四光",
    nameEn: "Li Siguang",
    gender: "male",
    era: "1889–1971",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "湖北",
    birthPlace: "黄冈",
    socialClass: "科学家",
    field: ["科学", "地质"],
    birth: {
      year: 1889,
      month: 10,
      day: 26,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["地质力学", "石油普查", "科学建国"],
    },
    bio: "中国现代地质学重要人物。",
    situation: "推动地质调查与石油勘探相关科学工作。",
    fitAssessment: "部分符合",
    analysisNotes: "偏财、印星事功叙事易套用。国家工业化与地质调查体制更关键。",
    classicalRefs: ["滴天髓：事功须看际遇"],
    sources: ["公开地质史人物年表"],
    counterexample: false,
  },
  {
    id: "liang-sicheng",
    name: "梁思成",
    nameEn: "Liang Sicheng",
    gender: "male",
    era: "1901–1972",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "广东/北京",
    birthPlace: "东京出生（籍贯广东新会）",
    socialClass: "建筑师/学者",
    field: ["建筑", "学术", "教育"],
    birth: {
      year: 1901,
      month: 4,
      day: 20,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["中国建筑史", "文物保护", "城市规划争议"],
    },
    bio: "中国建筑史与文物保护关键学者。",
    situation: "与林徽因等开展古建调查，参与现代建筑教育。",
    fitAssessment: "部分符合",
    analysisNotes: "印官学术叙事易贴合。留学训练与营造学社制度更关键。",
    classicalRefs: ["渊海子平：才官须看时势"],
    sources: ["公开建筑史人物年表"],
    counterexample: false,
  },
  {
    id: "ding-ling",
    name: "丁玲",
    nameEn: "Ding Ling",
    gender: "female",
    era: "1904–1986",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "湖南",
    birthPlace: "临澧",
    socialClass: "左翼文人",
    field: ["文学", "政治"],
    birth: {
      year: 1904,
      month: 10,
      day: 12,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["左翼文学", "性别议题", "政治运动冲击"],
    },
    bio: "现代女作家，左翼文学重要人物。",
    situation: "创作与政治身份交织，经历批判、劳改与复出。",
    fitAssessment: "不符合",
    analysisNotes:
      "反例：文名与政治遭遇剧烈起伏。文艺政策结构不能简化为格局旺衰。",
    classicalRefs: ["三命通会：岁运与人事并参"],
    sources: ["丁玲年谱通行材料"],
    counterexample: true,
  },
  {
    id: "shen-congwen",
    name: "沈从文",
    nameEn: "Shen Congwen",
    gender: "male",
    era: "1902–1988",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "湖南",
    birthPlace: "凤凰",
    socialClass: "文人/文物研究者",
    field: ["文学", "学术"],
    birth: {
      year: 1902,
      month: 12,
      day: 28,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["湘西书写", "转行文物", "诺奖呼声与政治"],
    },
    bio: "现代小说家，后转向文物与服饰史研究。",
    situation: "文学声望与政治压力并存，晚年学术转向。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤转印叙事易附会。政治运动与博物馆职业路径更关键。",
    classicalRefs: ["子平：才艺与名位须分看"],
    sources: ["沈从文年谱通行材料"],
    counterexample: false,
  },
  {
    id: "xu-beihong",
    name: "徐悲鸿",
    nameEn: "Xu Beihong",
    gender: "male",
    era: "1895–1953",
    dynastyOrPeriod: "近现代中国",
    country: "中国",
    region: "江苏",
    birthPlace: "宜兴",
    socialClass: "艺术家/教育家",
    field: ["艺术", "教育"],
    birth: {
      year: 1895,
      month: 7,
      day: 19,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["写实主义", "美术教育", "中西融合"],
    },
    bio: "中国现代美术教育关键人物，以奔马题材著称。",
    situation: "留学归来后主导美术学院教育方向。",
    fitAssessment: "部分符合",
    analysisNotes: "食伤生秀易套用。巴黎训练与国家美术体制更关键。",
    classicalRefs: ["子平：才艺成就须看时势"],
    sources: ["公开美术史人物年表"],
    counterexample: false,
  },
  {
    id: "zhang-jian",
    name: "张謇",
    nameEn: "Zhang Jian",
    gender: "male",
    era: "1853–1926",
    dynastyOrPeriod: "晚清民初",
    country: "中国",
    region: "江苏",
    birthPlace: "海门",
    socialClass: "士绅企业家",
    field: ["商业", "教育", "政治"],
    birth: {
      year: 1853,
      month: 7,
      day: 1,
      hour: null,
      calendar: "gregorian",
      precision: "exact-date",
      note: "出生日期通行；时辰未知。",
    },
    chartTags: {
      hourKnown: false,
      source: "computed",
      confidence: "medium",
      patternTags: ["状元实业", "南通现代化", "地方自治"],
    },
    bio: "晚清状元出身的实业家与教育家。",
    situation: "以大生纱厂等推动南通地方现代化。",
    fitAssessment: "部分符合",
    analysisNotes: "官印生财叙事极易附会。长江三角洲工业化与士绅网络更关键。",
    classicalRefs: ["渊海子平：财官印须分看时势"],
    sources: ["公开实业史人物年表"],
    counterexample: false,
  },
];